/** Auto-generated real landmarks (5A + verified Bing). Do not hand-edit. */

export const LANDMARKS_EXTRA = {
  anhui: [
    { cityId: "huangshan", cityName: "黄山", name: "皖南古村落－西递宏村", category: "历史人文", area: "黄山", location: "安徽省黄山市", source: "mct-5a", grade: "5A" },
    { cityId: "huangshan", cityName: "黄山", name: "古徽州文化旅游区", category: "历史人文", area: "黄山", location: "安徽省黄山市", source: "mct-5a", grade: "5A" },
    { cityId: "maanshan", cityName: "马鞍山", name: "长江采石矶文化生态旅游区", category: "海滨湖泊", area: "马鞍山", location: "安徽省马鞍山市", source: "mct-5a", grade: "5A" },
  ],
  beijing: [
    { cityId: "dongcheng", cityName: "东城", name: "颐和园", category: "历史人文", area: "东城", location: "北京市东城市", source: "mct-5a", grade: "5A" },
    { cityId: "dongcheng", cityName: "东城", name: "八达岭—慕田峪长城旅游区", category: "历史人文", area: "东城", location: "北京市东城市", source: "mct-5a", grade: "5A" },
    { cityId: "dongcheng", cityName: "东城", name: "明十三陵景区", category: "历史人文", area: "东城", location: "北京市东城市", source: "mct-5a", grade: "5A" },
    { cityId: "dongcheng", cityName: "东城", name: "恭王府景区", category: "历史人文", area: "东城", location: "北京市东城市", source: "mct-5a", grade: "5A" },
    { cityId: "dongcheng", cityName: "东城", name: "奥林匹克公园", category: "公园休闲", area: "东城", location: "北京市东城市", source: "mct-5a", grade: "5A" },
    { cityId: "dongcheng", cityName: "东城", name: "圆明园遗址公园景区", category: "公园休闲", area: "东城", location: "北京市东城市", source: "mct-5a", grade: "5A" },
    { cityId: "tongzhou", cityName: "通州", name: "通州）大运河文化旅游景区", category: "海滨湖泊", area: "通州", location: "北京市通州", source: "mct-5a", grade: "5A" },
  ],
  chongqing: [
    { cityId: "dazu", cityName: "大足", name: "石刻景区", category: "历史人文", area: "大足", location: "重庆市大足市", source: "mct-5a", grade: "5A" },
    { cityId: "chongqing", cityName: "重庆主城", name: "小三峡－小小三峡旅游区", category: "山地峡谷", area: "重庆主城", location: "重庆市重庆主城市", source: "mct-5a", grade: "5A" },
    { cityId: "chongqing", cityName: "重庆主城", name: "喀斯特旅游区", category: "历史人文", area: "重庆主城", location: "重庆市重庆主城市", source: "mct-5a", grade: "5A" },
    { cityId: "chongqing", cityName: "重庆主城", name: "桃花源旅游景区", category: "历史人文", area: "重庆主城", location: "重庆市重庆主城市", source: "mct-5a", grade: "5A" },
    { cityId: "chongqing", cityName: "重庆主城", name: "万盛黑山谷-龙鳞石海风景区", category: "山地峡谷", area: "重庆主城", location: "重庆市重庆主城市", source: "mct-5a", grade: "5A" },
    { cityId: "chongqing", cityName: "重庆主城", name: "金佛山景区", category: "山地峡谷", area: "重庆主城", location: "重庆市重庆主城市", source: "mct-5a", grade: "5A" },
    { cityId: "chongqing", cityName: "重庆主城", name: "四面山景区", category: "山地峡谷", area: "重庆主城", location: "重庆市重庆主城市", source: "mct-5a", grade: "5A" },
    { cityId: "chongqing", cityName: "重庆主城", name: "龙缸景区", category: "历史人文", area: "重庆主城", location: "重庆市重庆主城市", source: "mct-5a", grade: "5A" },
    { cityId: "chongqing", cityName: "重庆主城", name: "阿依河景区", category: "海滨湖泊", area: "重庆主城", location: "重庆市重庆主城市", source: "mct-5a", grade: "5A" },
    { cityId: "chongqing", cityName: "重庆主城", name: "濯水景区", category: "历史人文", area: "重庆主城", location: "重庆市重庆主城市", source: "mct-5a", grade: "5A" },
    { cityId: "chongqing", cityName: "重庆主城", name: "白帝城瞿塘峡景区", category: "山地峡谷", area: "重庆主城", location: "重庆市重庆主城市", source: "mct-5a", grade: "5A" },
    { cityId: "chongqing", cityName: "重庆主城", name: "武陵山大裂谷景区", category: "山地峡谷", area: "重庆主城", location: "重庆市重庆主城市", source: "mct-5a", grade: "5A" },
  ],
  fujian: [
    { cityId: "sanming", cityName: "三明", name: "泰宁风景旅游区", category: "历史人文", area: "三明", location: "福建省三明市", source: "mct-5a", grade: "5A" },
    { cityId: "ningde", cityName: "宁德", name: "白水洋鸳鸯溪旅游景区", category: "历史人文", area: "宁德", location: "福建省宁德市", source: "mct-5a", grade: "5A" },
    { cityId: "longyan", cityName: "龙岩", name: "古田旅游区", category: "历史人文", area: "龙岩", location: "福建省龙岩市", source: "mct-5a", grade: "5A" },
    { cityId: "putian", cityName: "莆田", name: "湄洲岛妈祖文化旅游区", category: "海滨湖泊", area: "莆田", location: "福建省莆田市", source: "mct-5a", grade: "5A" },
  ],
  gansu: [
    { cityId: "jiayuguan", cityName: "嘉峪关", name: "嘉峪关文物景区", category: "山地峡谷", area: "嘉峪关", location: "甘肃省嘉峪关市", source: "mct-5a", grade: "5A" },
    { cityId: "tianshui", cityName: "天水", name: "麦积山景区", category: "山地峡谷", area: "天水", location: "甘肃省天水市", source: "mct-5a", grade: "5A" },
    { cityId: "jiuquan", cityName: "酒泉", name: "鸣沙山月牙泉景区", category: "山地峡谷", area: "酒泉", location: "甘肃省酒泉市", source: "mct-5a", grade: "5A" },
    { cityId: "zhangye", cityName: "张掖", name: "七彩丹霞景区", category: "历史人文", area: "张掖", location: "甘肃省张掖市", source: "mct-5a", grade: "5A" },
    { cityId: "linxia", cityName: "临夏", name: "州炳灵寺世界文化遗产旅游区", category: "宗教寺庙", area: "临夏", location: "甘肃省临夏市", source: "mct-5a", grade: "5A" },
    { cityId: "gannan", cityName: "甘南", name: "州冶力关旅游区", category: "山地峡谷", area: "甘南", location: "甘肃省甘南市", source: "mct-5a", grade: "5A" },
  ],
  guangdong: [
    { cityId: "guangzhou", cityName: "广州", name: "番禺区长隆旅游度假区", category: "历史人文", area: "广州", location: "广东省广州", source: "mct-5a", grade: "5A" },
    { cityId: "shenzhen", cityName: "深圳", name: "南山区华侨城旅游度假区", category: "山地峡谷", area: "深圳", location: "广东省深圳市", source: "mct-5a", grade: "5A" },
    { cityId: "guangzhou", cityName: "广州", name: "白云区白云山景区", category: "山地峡谷", area: "广州", location: "广东省广州", source: "mct-5a", grade: "5A" },
    { cityId: "meizhou", cityName: "梅州", name: "梅县区雁南飞茶田景区", category: "历史人文", area: "梅州", location: "广东省梅州", source: "mct-5a", grade: "5A" },
    { cityId: "shenzhen", cityName: "深圳", name: "龙华区观澜湖休闲旅游区", category: "海滨湖泊", area: "深圳", location: "广东省深圳市", source: "mct-5a", grade: "5A" },
    { cityId: "qingyuan", cityName: "清远", name: "连州市地下河旅游景区", category: "海滨湖泊", area: "清远", location: "广东省清远市", source: "mct-5a", grade: "5A" },
    { cityId: "shaoguan", cityName: "韶关", name: "仁化县丹霞山景区", category: "山地峡谷", area: "韶关", location: "广东省韶关市", source: "mct-5a", grade: "5A" },
    { cityId: "foshan", cityName: "佛山", name: "南海区西樵山景区", category: "山地峡谷", area: "佛山", location: "广东省佛山市", source: "mct-5a", grade: "5A" },
    { cityId: "huizhou", cityName: "惠州", name: "博罗县罗浮山景区", category: "山地峡谷", area: "惠州", location: "广东省惠州", source: "mct-5a", grade: "5A" },
    { cityId: "foshan", cityName: "佛山", name: "顺德区长鹿旅游休博园", category: "历史人文", area: "佛山", location: "广东省佛山市", source: "mct-5a", grade: "5A" },
    { cityId: "yangjiang", cityName: "阳江", name: "江城区海陵岛大角湾海上丝路旅游区", category: "海滨湖泊", area: "阳江", location: "广东省阳江市", source: "mct-5a", grade: "5A" },
    { cityId: "zhongshan", cityName: "中山", name: "孙中山故里旅游区", category: "山地峡谷", area: "中山", location: "广东省中山市", source: "mct-5a", grade: "5A" },
    { cityId: "huizhou", cityName: "惠州", name: "惠城区惠州西湖旅游景区", category: "海滨湖泊", area: "惠州", location: "广东省惠州", source: "mct-5a", grade: "5A" },
    { cityId: "jiangmen", cityName: "江门", name: "开平市开平碉楼文化旅游区", category: "历史人文", area: "江门", location: "广东省江门市", source: "mct-5a", grade: "5A" },
  ],
  guangxi: [
    { cityId: "guilin", cityName: "桂林", name: "独秀峰靖江王城景区", category: "海滨湖泊", area: "桂林", location: "广西壮族自治区桂林市", source: "mct-5a", grade: "5A" },
    { cityId: "nanning", cityName: "南宁", name: "青秀山风景名胜旅游区", category: "山地峡谷", area: "南宁", location: "广西壮族自治区南宁市", source: "mct-5a", grade: "5A" },
    { cityId: "guilin", cityName: "桂林", name: "两江四湖象山景区", category: "海滨湖泊", area: "桂林", location: "广西壮族自治区桂林市", source: "mct-5a", grade: "5A" },
    { cityId: "chongzuo", cityName: "崇左", name: "德天跨国瀑布景区", category: "山地峡谷", area: "崇左", location: "广西壮族自治区崇左市", source: "mct-5a", grade: "5A" },
    { cityId: "beihai", cityName: "北海", name: "涠洲岛南湾鳄鱼山景区", category: "海滨湖泊", area: "北海", location: "广西壮族自治区北海市", source: "mct-5a", grade: "5A" },
  ],
  guizhou: [
    { cityId: "anshun", cityName: "安顺", name: "西秀区龙宫景区", category: "历史人文", area: "安顺", location: "贵州省安顺市", source: "mct-5a", grade: "5A" },
    { cityId: "guiyang", cityName: "贵阳", name: "花溪区青岩古镇景区", category: "古镇街区", area: "贵阳", location: "贵州省贵阳市", source: "mct-5a", grade: "5A" },
    { cityId: "tongren", cityName: "铜仁", name: "江口县梵净山旅游区", category: "海滨湖泊", area: "铜仁", location: "贵州省铜仁市", source: "mct-5a", grade: "5A" },
    { cityId: "qiandongnan", cityName: "黔东南", name: "州镇远县镇远古城旅游景区", category: "古镇街区", area: "黔东南", location: "贵州省黔东南市", source: "mct-5a", grade: "5A" },
    { cityId: "qianxinan", cityName: "黔西南", name: "州万峰林景区", category: "山地峡谷", area: "黔西南", location: "贵州省黔西南市", source: "mct-5a", grade: "5A" },
  ],
  hainan: [
    { cityId: "sanya", cityName: "三亚", name: "南山大小洞天旅游区", category: "山地峡谷", area: "三亚", location: "海南省三亚市", source: "mct-5a", grade: "5A" },
    { cityId: "lingshui", cityName: "陵水", name: "县分界洲岛旅游区", category: "海滨湖泊", area: "陵水", location: "海南省陵水市", source: "mct-5a", grade: "5A" },
    { cityId: "sanya", cityName: "三亚", name: "天涯海角游览区", category: "历史人文", area: "三亚", location: "海南省三亚市", source: "mct-5a", grade: "5A" },
  ],
  hebei: [
    { cityId: "chengde", cityName: "承德", name: "承德避暑山庄及周围寺庙景区", category: "宗教寺庙", area: "承德", location: "河北省承德市", source: "mct-5a", grade: "5A" },
    { cityId: "tangshan", cityName: "唐山", name: "南湖开滦旅游景区", category: "海滨湖泊", area: "唐山", location: "河北省唐山市", source: "mct-5a", grade: "5A" },
  ],
  heilongjiang: [
    { cityId: "yichun", cityName: "伊春", name: "林海奇石景区", category: "历史人文", area: "伊春", location: "黑龙江省伊春市", source: "mct-5a", grade: "5A" },
  ],
  henan: [
    { cityId: "zhengzhou", cityName: "郑州", name: "嵩山少林景区", category: "山地峡谷", area: "郑州", location: "河南省郑州", source: "mct-5a", grade: "5A" },
    { cityId: "jiaozuo", cityName: "焦作", name: "云台山－神农山－青天河风景区", category: "海滨湖泊", area: "焦作", location: "河南省焦作市", source: "mct-5a", grade: "5A" },
    { cityId: "pingdingshan", cityName: "平顶山", name: "尧山－中原大佛景区", category: "山地峡谷", area: "平顶山", location: "河南省平顶山市", source: "mct-5a", grade: "5A" },
    { cityId: "luoyang", cityName: "洛阳", name: "老君山－鸡冠洞旅游区", category: "山地峡谷", area: "洛阳", location: "河南省洛阳市", source: "mct-5a", grade: "5A" },
    { cityId: "nanyang", cityName: "南阳", name: "西峡恐龙遗迹园-伏牛山-老界岭旅游区", category: "山地峡谷", area: "南阳", location: "河南省南阳市", source: "mct-5a", grade: "5A" },
    { cityId: "anyang", cityName: "安阳", name: "红旗渠－太行大峡谷旅游景区", category: "山地峡谷", area: "安阳", location: "河南省安阳市", source: "mct-5a", grade: "5A" },
    { cityId: "zhoukou", cityName: "周口", name: "太昊伏羲陵文化旅游区", category: "历史人文", area: "周口", location: "河南省周口市", source: "mct-5a", grade: "5A" },
  ],
  hubei: [
    { cityId: "wuhan", cityName: "武汉", name: "黄鹤楼公园", category: "公园休闲", area: "武汉", location: "湖北省武汉市", source: "mct-5a", grade: "5A" },
    { cityId: "yichang", cityName: "宜昌", name: "三峡大坝－屈原故里文化旅游区", category: "山地峡谷", area: "宜昌", location: "湖北省宜昌市", source: "mct-5a", grade: "5A" },
    { cityId: "enshi", cityName: "恩施", name: "州神农溪纤夫文化旅游区", category: "历史人文", area: "恩施", location: "湖北省恩施市", source: "mct-5a", grade: "5A" },
    { cityId: "wuhan", cityName: "武汉", name: "木兰文化生态旅游区", category: "历史人文", area: "武汉", location: "湖北省武汉市", source: "mct-5a", grade: "5A" },
    { cityId: "enshi", cityName: "恩施", name: "州恩施大峡谷景区", category: "山地峡谷", area: "恩施", location: "湖北省恩施市", source: "mct-5a", grade: "5A" },
    { cityId: "xianning", cityName: "咸宁", name: "三国赤壁古战场景区", category: "历史人文", area: "咸宁", location: "湖北省咸宁市", source: "mct-5a", grade: "5A" },
    { cityId: "enshi", cityName: "恩施", name: "州腾龙洞景区", category: "山地峡谷", area: "恩施", location: "湖北省恩施市", source: "mct-5a", grade: "5A" },
    { cityId: "yichang", cityName: "宜昌", name: "三峡大瀑布景区", category: "山地峡谷", area: "宜昌", location: "湖北省宜昌市", source: "mct-5a", grade: "5A" },
    { cityId: "huanggang", cityName: "黄冈", name: "麻城龟峰山景区", category: "山地峡谷", area: "黄冈", location: "湖北省黄冈市", source: "mct-5a", grade: "5A" },
  ],
  hunan: [
    { cityId: "zhangjiajie", cityName: "张家界", name: "武陵源－天门山旅游区", category: "山地峡谷", area: "张家界", location: "湖南省张家界市", source: "mct-5a", grade: "5A" },
    { cityId: "hengyang", cityName: "衡阳", name: "衡山旅游区", category: "山地峡谷", area: "衡阳", location: "湖南省衡阳市", source: "mct-5a", grade: "5A" },
    { cityId: "yueyang", cityName: "岳阳", name: "岳阳楼－君山岛景区", category: "海滨湖泊", area: "岳阳", location: "湖南省岳阳市", source: "mct-5a", grade: "5A" },
    { cityId: "changsha", cityName: "长沙", name: "岳麓山-橘子洲旅游区", category: "山地峡谷", area: "长沙", location: "湖南省长沙市", source: "mct-5a", grade: "5A" },
    { cityId: "changsha", cityName: "长沙", name: "花明楼景区", category: "历史人文", area: "长沙", location: "湖南省长沙市", source: "mct-5a", grade: "5A" },
    { cityId: "xiangxi", cityName: "湘西", name: "州吉首市矮寨十八洞德夯大峡谷景区", category: "山地峡谷", area: "湘西", location: "湖南省湘西市", source: "mct-5a", grade: "5A" },
    { cityId: "fenghuang", cityName: "凤凰", name: "湘西州凤凰古城旅游区", category: "古镇街区", area: "凤凰", location: "湖南省凤凰市", source: "mct-5a", grade: "5A" },
  ],
  jiangsu: [
    { cityId: "suzhou", cityName: "苏州", name: "苏州园林拙政园－留园－虎丘", category: "公园休闲", area: "苏州", location: "江苏省苏州", source: "mct-5a", grade: "5A" },
    { cityId: "suzhou", cityName: "苏州", name: "周庄古镇景区", category: "古镇街区", area: "苏州", location: "江苏省苏州", source: "mct-5a", grade: "5A" },
    { cityId: "nanjing", cityName: "南京", name: "钟山风景名胜区－中山陵园风景区", category: "山地峡谷", area: "南京", location: "江苏省南京市", source: "mct-5a", grade: "5A" },
    { cityId: "wuxi", cityName: "无锡", name: "中央电视台无锡影视基地三国水浒城景区", category: "历史人文", area: "无锡", location: "江苏省无锡市", source: "mct-5a", grade: "5A" },
    { cityId: "suzhou", cityName: "苏州", name: "同里古镇景区", category: "古镇街区", area: "苏州", location: "江苏省苏州", source: "mct-5a", grade: "5A" },
    { cityId: "nanjing", cityName: "南京", name: "夫子庙－秦淮风光带", category: "宗教寺庙", area: "南京", location: "江苏省南京市", source: "mct-5a", grade: "5A" },
    { cityId: "changzhou", cityName: "常州", name: "环球恐龙城休闲旅游区", category: "历史人文", area: "常州", location: "江苏省常州", source: "mct-5a", grade: "5A" },
    { cityId: "zhenjiang", cityName: "镇江", name: "金山焦山北固山风景区", category: "山地峡谷", area: "镇江", location: "江苏省镇江市", source: "mct-5a", grade: "5A" },
    { cityId: "wuxi", cityName: "无锡", name: "鼋头渚旅游风景区", category: "历史人文", area: "无锡", location: "江苏省无锡市", source: "mct-5a", grade: "5A" },
    { cityId: "suzhou", cityName: "苏州", name: "太湖旅游区", category: "海滨湖泊", area: "苏州", location: "江苏省苏州", source: "mct-5a", grade: "5A" },
    { cityId: "suzhou", cityName: "苏州", name: "沙家浜－虞山尚湖旅游区", category: "海滨湖泊", area: "苏州", location: "江苏省苏州", source: "mct-5a", grade: "5A" },
    { cityId: "huaian", cityName: "淮安", name: "周恩来故里景区", category: "历史人文", area: "淮安", location: "江苏省淮安市", source: "mct-5a", grade: "5A" },
    { cityId: "changzhou", cityName: "常州", name: "春秋淹城旅游区", category: "历史人文", area: "常州", location: "江苏省常州", source: "mct-5a", grade: "5A" },
  ],
  jiangxi: [
    { cityId: "jiujiang", cityName: "九江", name: "庐山市庐山风景名胜区", category: "山地峡谷", area: "九江", location: "江西省九江市", source: "mct-5a", grade: "5A" },
    { cityId: "jian", cityName: "吉安", name: "井冈山市井冈山风景旅游区", category: "山地峡谷", area: "吉安", location: "江西省吉安市", source: "mct-5a", grade: "5A" },
    { cityId: "shangrao", cityName: "上饶", name: "玉山县三清山风景区", category: "山地峡谷", area: "上饶", location: "江西省上饶市", source: "mct-5a", grade: "5A" },
    { cityId: "yingtan", cityName: "鹰潭", name: "贵溪市龙虎山风景名胜区", category: "山地峡谷", area: "鹰潭", location: "江西省鹰潭市", source: "mct-5a", grade: "5A" },
    { cityId: "shangrao", cityName: "上饶", name: "婺源县江湾景区", category: "海滨湖泊", area: "上饶", location: "江西省上饶市", source: "mct-5a", grade: "5A" },
    { cityId: "jingdezhen", cityName: "景德镇", name: "昌江区古窑民俗博览区", category: "海滨湖泊", area: "景德镇", location: "江西省景德镇市", source: "mct-5a", grade: "5A" },
    { cityId: "ganzhou", cityName: "赣州", name: "瑞金市共和国摇篮景区", category: "历史人文", area: "赣州", location: "江西省赣州", source: "mct-5a", grade: "5A" },
    { cityId: "yichun", cityName: "宜春", name: "袁州区明月山旅游区", category: "山地峡谷", area: "宜春", location: "江西省宜春市", source: "mct-5a", grade: "5A" },
    { cityId: "fuzhou-jx", cityName: "抚州", name: "资溪县大觉山景区", category: "山地峡谷", area: "抚州", location: "江西省抚州", source: "mct-5a", grade: "5A" },
    { cityId: "shangrao", cityName: "上饶", name: "弋阳县龟峰景区", category: "山地峡谷", area: "上饶", location: "江西省上饶市", source: "mct-5a", grade: "5A" },
    { cityId: "nanchang", cityName: "南昌", name: "东湖区滕王阁旅游区", category: "海滨湖泊", area: "南昌", location: "江西省南昌市", source: "mct-5a", grade: "5A" },
    { cityId: "pingxiang", cityName: "萍乡", name: "芦溪县萍乡武功山景区", category: "山地峡谷", area: "萍乡", location: "江西省萍乡市", source: "mct-5a", grade: "5A" },
    { cityId: "jiujiang", cityName: "九江", name: "永修县庐山西海景区", category: "山地峡谷", area: "九江", location: "江西省九江市", source: "mct-5a", grade: "5A" },
    { cityId: "shangrao", cityName: "上饶", name: "篁岭景区", category: "历史人文", area: "上饶", location: "江西省上饶市", source: "mct-5a", grade: "5A" },
  ],
  jilin: [
    { cityId: "changbaishan", cityName: "长白山", name: "延边朝鲜族自治州长白山景区", category: "山地峡谷", area: "长白山", location: "吉林省长白山市", source: "mct-5a", grade: "5A" },
    { cityId: "changchun", cityName: "长春", name: "伪满皇宫博物馆", category: "博物馆", area: "长春", location: "吉林省长春市", source: "mct-5a", grade: "5A" },
    { cityId: "yanbian", cityName: "延边", name: "州六鼎山文化旅游区", category: "山地峡谷", area: "延边", location: "吉林省延边市", source: "mct-5a", grade: "5A" },
    { cityId: "changchun", cityName: "长春", name: "世界雕塑公园景区", category: "公园休闲", area: "长春", location: "吉林省长春市", source: "mct-5a", grade: "5A" },
  ],
  liaoning: [
    { cityId: "shenyang", cityName: "沈阳", name: "沈阳植物园", category: "公园休闲", area: "沈阳", location: "辽宁省沈阳市", source: "mct-5a", grade: "5A" },
    { cityId: "dalian", cityName: "大连", name: "老虎滩海洋公园—老虎滩极地馆", category: "主题乐园", area: "大连", location: "辽宁省大连市", source: "mct-5a", grade: "5A" },
  ],
  neimenggu: [
    { cityId: "hulunbuir", cityName: "呼伦贝尔", name: "中俄边境旅游区", category: "历史人文", area: "呼伦贝尔", location: "内蒙古自治区呼伦贝尔市", source: "mct-5a", grade: "5A" },
    { cityId: "alxa", cityName: "阿拉善", name: "盟胡杨林旅游区", category: "历史人文", area: "阿拉善", location: "内蒙古自治区阿拉善市", source: "mct-5a", grade: "5A" },
    { cityId: "hulunbuir", cityName: "呼伦贝尔", name: "呼伦贝尔大草原莫尔格勒河景区", category: "海滨湖泊", area: "呼伦贝尔", location: "内蒙古自治区呼伦贝尔市", source: "mct-5a", grade: "5A" },
    { cityId: "hohhot", cityName: "呼和浩特", name: "老牛湾黄河大峡谷旅游区", category: "海滨湖泊", area: "呼和浩特", location: "内蒙古自治区呼和浩特市", source: "mct-5a", grade: "5A" },
  ],
  ningxia: [
    { cityId: "yinchuan", cityName: "银川", name: "宁夏镇北堡西部影视城", category: "历史人文", area: "银川", location: "宁夏回族自治区银川市", source: "mct-5a", grade: "5A" },
    { cityId: "qingtongxia", cityName: "青铜峡", name: "吴忠市青铜峡黄河大峡谷旅游区", category: "海滨湖泊", area: "青铜峡", location: "宁夏回族自治区青铜峡市", source: "mct-5a", grade: "5A" },
    { cityId: "guyuan", cityName: "固原", name: "六盘山红军长征旅游区", category: "山地峡谷", area: "固原", location: "宁夏回族自治区固原市", source: "mct-5a", grade: "5A" },
  ],
  qinghai: [
    { cityId: "qinghai-lake", cityName: "青海湖", name: "湖风景区", category: "海滨湖泊", area: "青海湖", location: "青海省青海湖市", source: "mct-5a", grade: "5A" },
  ],
  shaanxi: [
    { cityId: "xian", cityName: "西安", name: "秦始皇帝陵博物院景区", category: "博物馆", area: "西安", location: "陕西省西安市", source: "mct-5a", grade: "5A" },
    { cityId: "xian", cityName: "西安", name: "大雁塔－大唐芙蓉园景区", category: "历史人文", area: "西安", location: "陕西省西安市", source: "mct-5a", grade: "5A" },
    { cityId: "huashan", cityName: "华山", name: "渭南市华山风景区", category: "山地峡谷", area: "华山", location: "陕西省华山市", source: "mct-5a", grade: "5A" },
    { cityId: "baoji", cityName: "宝鸡", name: "法门文化景区", category: "历史人文", area: "宝鸡", location: "陕西省宝鸡市", source: "mct-5a", grade: "5A" },
    { cityId: "baoji", cityName: "宝鸡", name: "太白山旅游景区", category: "山地峡谷", area: "宝鸡", location: "陕西省宝鸡市", source: "mct-5a", grade: "5A" },
    { cityId: "xian", cityName: "西安", name: "城墙碑林历史文化景区", category: "历史人文", area: "西安", location: "陕西省西安市", source: "mct-5a", grade: "5A" },
    { cityId: "yanan", cityName: "延安", name: "延安革命纪念地景区", category: "历史人文", area: "延安", location: "陕西省延安市", source: "mct-5a", grade: "5A" },
    { cityId: "xian", cityName: "西安", name: "大明宫旅游景区", category: "历史人文", area: "西安", location: "陕西省西安市", source: "mct-5a", grade: "5A" },
    { cityId: "yanan", cityName: "延安", name: "延川黄河乾坤湾景区", category: "海滨湖泊", area: "延安", location: "陕西省延安市", source: "mct-5a", grade: "5A" },
  ],
  shandong: [
    { cityId: "yantai", cityName: "烟台", name: "蓬莱阁-三仙山-八仙过海旅游区", category: "山地峡谷", area: "烟台", location: "山东省烟台市", source: "mct-5a", grade: "5A" },
    { cityId: "jining", cityName: "济宁", name: "明故城三孔旅游区", category: "历史人文", area: "济宁", location: "山东省济宁市", source: "mct-5a", grade: "5A" },
    { cityId: "yantai", cityName: "烟台", name: "南山景区", category: "山地峡谷", area: "烟台", location: "山东省烟台市", source: "mct-5a", grade: "5A" },
    { cityId: "jinan", cityName: "济南", name: "天下第一泉景区", category: "历史人文", area: "济南", location: "山东省济南市", source: "mct-5a", grade: "5A" },
    { cityId: "weihai", cityName: "威海", name: "威海华夏城景区", category: "历史人文", area: "威海", location: "山东省威海市", source: "mct-5a", grade: "5A" },
    { cityId: "dongying", cityName: "东营", name: "黄河口生态旅游区", category: "海滨湖泊", area: "东营", location: "山东省东营市", source: "mct-5a", grade: "5A" },
    { cityId: "linyi", cityName: "临沂", name: "萤火虫水洞地下大峡谷旅游区", category: "山地峡谷", area: "临沂", location: "山东省临沂市", source: "mct-5a", grade: "5A" },
    { cityId: "qingdao", cityName: "青岛", name: "奥帆海洋文化旅游区", category: "历史人文", area: "青岛", location: "山东省青岛市", source: "mct-5a", grade: "5A" },
  ],
  shanghai: [
    { cityId: "huangpu", cityName: "黄浦", name: "东方明珠广播电视塔", category: "历史人文", area: "黄浦", location: "上海市黄浦市", source: "mct-5a", grade: "5A" },
    { cityId: "huangpu", cityName: "黄浦", name: "野生动物园", category: "主题乐园", area: "黄浦", location: "上海市黄浦市", source: "mct-5a", grade: "5A" },
    { cityId: "huangpu", cityName: "黄浦", name: "科技馆", category: "博物馆", area: "黄浦", location: "上海市黄浦市", source: "mct-5a", grade: "5A" },
    { cityId: "huangpu", cityName: "黄浦", name: "中国共产党一大二大四大纪念馆景区", category: "博物馆", area: "黄浦", location: "上海市黄浦市", source: "mct-5a", grade: "5A" },
    { cityId: "huangpu", cityName: "黄浦", name: "西沙明珠湖景区", category: "海滨湖泊", area: "黄浦", location: "上海市黄浦市", source: "mct-5a", grade: "5A" },
  ],
  shanxi: [
    { cityId: "pingyao", cityName: "平遥", name: "晋中市平遥古城景区", category: "古镇街区", area: "平遥", location: "山西省平遥市", source: "mct-5a", grade: "5A" },
    { cityId: "taiyuan", cityName: "太原", name: "晋祠天龙山景区", category: "宗教寺庙", area: "太原", location: "山西省太原市", source: "mct-5a", grade: "5A" },
  ],
  sichuan: [
    { cityId: "chengdu", cityName: "成都", name: "青城山－都江堰旅游景区", category: "海滨湖泊", area: "成都", location: "四川省成都市", source: "mct-5a", grade: "5A" },
    { cityId: "aba", cityName: "阿坝", name: "州九寨沟景区", category: "历史人文", area: "阿坝", location: "四川省阿坝市", source: "mct-5a", grade: "5A" },
    { cityId: "aba", cityName: "阿坝", name: "州黄龙风景名胜区", category: "历史人文", area: "阿坝", location: "四川省阿坝市", source: "mct-5a", grade: "5A" },
    { cityId: "mianyang", cityName: "绵阳", name: "羌城旅游区", category: "历史人文", area: "绵阳", location: "四川省绵阳市", source: "mct-5a", grade: "5A" },
    { cityId: "aba", cityName: "阿坝", name: "州汶川特别旅游区", category: "历史人文", area: "阿坝", location: "四川省阿坝市", source: "mct-5a", grade: "5A" },
    { cityId: "garze", cityName: "甘孜", name: "州海螺沟景区", category: "历史人文", area: "甘孜", location: "四川省甘孜市", source: "mct-5a", grade: "5A" },
    { cityId: "garze", cityName: "甘孜", name: "州稻城亚丁旅游景区", category: "历史人文", area: "甘孜", location: "四川省甘孜市", source: "mct-5a", grade: "5A" },
    { cityId: "aba", cityName: "阿坝", name: "州四姑娘山景区", category: "山地峡谷", area: "阿坝", location: "四川省阿坝市", source: "mct-5a", grade: "5A" },
    { cityId: "chengdu", cityName: "成都", name: "天台山景区", category: "山地峡谷", area: "成都", location: "四川省成都市", source: "mct-5a", grade: "5A" },
  ],
  tianjin: [
    { cityId: "heping", cityName: "和平", name: "古文化街旅游区津门故里", category: "美食购物", area: "和平", location: "天津市和平市", source: "mct-5a", grade: "5A" },
    { cityId: "heping", cityName: "和平", name: "盘山风景名胜区", category: "山地峡谷", area: "和平", location: "天津市和平市", source: "mct-5a", grade: "5A" },
  ],
  xinjiang: [
    { cityId: "kanas", cityName: "喀纳斯", name: "阿勒泰地区喀纳斯景区", category: "历史人文", area: "喀纳斯", location: "新疆维吾尔自治区喀纳斯市", source: "mct-5a", grade: "5A" },
    { cityId: "nalati", cityName: "那拉提", name: "伊犁哈萨克自治州那拉提旅游风景区", category: "历史人文", area: "那拉提", location: "新疆维吾尔自治区那拉提市", source: "mct-5a", grade: "5A" },
    { cityId: "altay", cityName: "阿勒泰", name: "地区可可托海景区", category: "历史人文", area: "阿勒泰", location: "新疆维吾尔自治区阿勒泰市", source: "mct-5a", grade: "5A" },
    { cityId: "kashgar", cityName: "喀什", name: "地区金湖杨景区", category: "海滨湖泊", area: "喀什", location: "新疆维吾尔自治区喀什市", source: "mct-5a", grade: "5A" },
    { cityId: "urumqi", cityName: "乌鲁木齐", name: "天山大峡谷", category: "山地峡谷", area: "乌鲁木齐", location: "新疆维吾尔自治区乌鲁木齐市", source: "mct-5a", grade: "5A" },
    { cityId: "kashgar", cityName: "喀什", name: "地区喀什古城景区", category: "古镇街区", area: "喀什", location: "新疆维吾尔自治区喀什市", source: "mct-5a", grade: "5A" },
    { cityId: "kashgar", cityName: "喀什", name: "地区帕米尔旅游区", category: "历史人文", area: "喀什", location: "新疆维吾尔自治区喀什市", source: "mct-5a", grade: "5A" },
    { cityId: "sayram", cityName: "赛里木湖", name: "博尔塔拉蒙古自治州赛里木湖景区", category: "海滨湖泊", area: "赛里木湖", location: "新疆维吾尔自治区赛里木湖市", source: "mct-5a", grade: "5A" },
    { cityId: "altay", cityName: "阿勒泰", name: "兵团十师185团白沙湖景区阿勒泰地区", category: "海滨湖泊", area: "阿勒泰", location: "新疆维吾尔自治区阿勒泰市", source: "mct-5a", grade: "5A" },
  ],
  yunnan: [
    { cityId: "dali", cityName: "大理", name: "州崇圣寺三塔文化旅游区", category: "宗教寺庙", area: "大理", location: "云南省大理市", source: "mct-5a", grade: "5A" },
    { cityId: "kunming", cityName: "昆明", name: "昆明世博园景区", category: "历史人文", area: "昆明", location: "云南省昆明市", source: "mct-5a", grade: "5A" },
    { cityId: "baoshan", cityName: "保山", name: "火山热海旅游区", category: "山地峡谷", area: "保山", location: "云南省保山市", source: "mct-5a", grade: "5A" },
  ],
  zhejiang: [
    { cityId: "hangzhou", cityName: "杭州", name: "杭州西湖风景区", category: "海滨湖泊", area: "杭州", location: "浙江省杭州", source: "mct-5a", grade: "5A" },
    { cityId: "jiaxing", cityName: "嘉兴", name: "乌镇古镇旅游区", category: "古镇街区", area: "嘉兴", location: "浙江省嘉兴市", source: "mct-5a", grade: "5A" },
    { cityId: "ningbo", cityName: "宁波", name: "溪口－滕头旅游景区", category: "历史人文", area: "宁波", location: "浙江省宁波市", source: "mct-5a", grade: "5A" },
    { cityId: "shaoxing", cityName: "绍兴", name: "鲁迅故里沈园景区", category: "历史人文", area: "绍兴", location: "浙江省绍兴市", source: "mct-5a", grade: "5A" },
    { cityId: "quzhou", cityName: "衢州", name: "根宫佛国文化旅游区", category: "历史人文", area: "衢州", location: "浙江省衢州", source: "mct-5a", grade: "5A" },
    { cityId: "jiaxing", cityName: "嘉兴", name: "西塘古镇旅游景区", category: "古镇街区", area: "嘉兴", location: "浙江省嘉兴市", source: "mct-5a", grade: "5A" },
    { cityId: "quzhou", cityName: "衢州", name: "江郎山廿八都旅游区", category: "海滨湖泊", area: "衢州", location: "浙江省衢州", source: "mct-5a", grade: "5A" },
    { cityId: "ningbo", cityName: "宁波", name: "天一阁月湖景区", category: "海滨湖泊", area: "宁波", location: "浙江省宁波市", source: "mct-5a", grade: "5A" },
    { cityId: "wenzhou", cityName: "温州", name: "刘伯温故里景区", category: "历史人文", area: "温州", location: "浙江省温州", source: "mct-5a", grade: "5A" },
    { cityId: "taizhou_tz", cityName: "台州", name: "台州府城文化旅游区", category: "历史人文", area: "台州", location: "浙江省台州", source: "mct-5a", grade: "5A" },
    { cityId: "jinhua", cityName: "金华", name: "双龙风景旅游区", category: "历史人文", area: "金华", location: "浙江省金华市", source: "mct-5a", grade: "5A" },
  ],
};
