/**
 * 防脱养发专项食谱（早 / 中 / 晚）
 *
 * 定位：以毛囊营养支持与脂溢/雄脱生活方式干预为目标的三餐方案；
 *       可作为「AGA增肌」系列的清淡/非训练日替代，也可独立 7 日轮换。
 *
 * 营养师原则：
 * - 每餐足量优质蛋白（角蛋白原料），避免长期低蛋白节食；
 * - 铁（优先血红素 + 维C）、锌、铜适量食物来源，勿迷信大剂量生物素补剂；
 * - Ω-3、维E、多酚：辅助控炎、改善头皮微环境；
 * - 控酒精、高糖饮料、过度油炸辛辣；晚餐清淡利睡眠；
 * - 膳食不能替代米诺地尔/非那雄胺及皮肤科治疗。
 */

function dishes(lines) {
  return lines.join('\n');
}

function hairNotes({ focus, protein, calories, keyNutrients, tip, effects }) {
  return [
    `功效：${focus}`,
    `补什么：${keyNutrients}`,
    `作用：${effects || '支持毛囊营养环境与控油清淡饮食，辅助外用药疗程期间的膳食管理。'}`,
    `营养：优质蛋白约 ${protein}；参考热量约 ${calories} 千卡/餐。`,
    tip ? `贴士：${tip}` : null,
    '说明：营养支持毛发生长环境，不等于治愈脱发；缺铁/维D等须化验后遵医嘱补充。',
  ].filter(Boolean).join('\n');
}

function recipe(def) {
  return {
    prepMinutes: 30,
    tags: '',
    ...def,
    ingredients: Array.isArray(def.ingredients) ? dishes(def.ingredients) : def.ingredients,
    steps: Array.isArray(def.steps) ? def.steps.join('\n') : def.steps,
  };
}

/* ========== 早餐 × 7 ========== */

export const HAIR_CARE_BREAKFAST = [
  recipe({
    templateKey: 'hair-care-bf-d1',
    title: '防脱养发｜鸡蛋菠菜核桃燕麦',
    mealType: '早餐',
    ingredients: [
      '主食｜纯燕麦 45g（干）｜约 165 千卡',
      '蛋白｜水煮蛋 2 个｜约 150 千卡',
      '蔬菜｜菠菜 80g（焯水）｜约 20 千卡',
      '蛋白｜无乳糖无糖酸奶 150g｜约 80 千卡',
      '脂肪｜核桃仁 10g｜约 65 千卡',
      '水果｜橙子 1/2 个｜约 35 千卡',
    ],
    steps: [
      '燕麦用清水或无乳糖奶煮熟；菠菜焯水挤干切碎拌入。',
      '水煮蛋去壳；酸奶与核桃、橙瓣同盘。',
      '维C与深绿叶菜同餐，照顾非血红素铁吸收。',
      '不放糖浆果酱。',
    ],
    notes: hairNotes({
      focus: '经典养发早餐：卵磷脂/生物素（蛋）+ 叶酸铁（菠菜）+ ALA（核桃）。',
      protein: '28～34g',
      calories: 515,
      keyNutrients: '生物素、叶酸、铁、Ω-3（ALA）、维C',
      tip: '菠菜务必焯水减草酸；结石风险高者深绿叶菜轮换生菜。',
    }),
    prepMinutes: 20,
    calories: 515,
    tags: '早餐,防脱,养发,高蛋白,生物素,叶酸',
  }),
  recipe({
    templateKey: 'hair-care-bf-d2',
    title: '防脱养发｜三文鱼全麦牛油果吐司',
    mealType: '早餐',
    ingredients: [
      '主食｜全麦吐司 2 片｜约 150 千卡',
      '蛋白｜清蒸三文鱼 50g｜约 100 千卡',
      '脂肪｜牛油果 40g｜约 65 千卡',
      '蔬菜｜番茄片 + 生菜｜约 25 千卡',
      '蛋白｜无乳糖低脂奶 200mL｜约 80 千卡',
      '水果｜蓝莓 60g｜约 35 千卡',
    ],
    steps: [
      '三文鱼蒸熟压碎铺吐司，叠牛油果番茄生菜。',
      '可挤柠檬；奶与蓝莓搭配饮用/食用。',
      '每周 2 次深海鱼即可，不必每日。',
    ],
    notes: hairNotes({
      focus: 'EPA/DHA 支持头皮抗炎环境，搭配维E与花青素。',
      protein: '26～32g',
      calories: 455,
      keyNutrients: 'Ω-3、维E、优质蛋白、花青素、钙',
      tip: '头皮油脂很重时可减少牛油果至 25g。',
    }),
    prepMinutes: 20,
    calories: 455,
    tags: '早餐,防脱,养发,Ω-3,抗炎',
  }),
  recipe({
    templateKey: 'hair-care-bf-d3',
    title: '防脱养发｜鸡胸紫薯南瓜籽碗',
    mealType: '早餐',
    ingredients: [
      '主食｜蒸紫薯 150g｜约 135 千卡',
      '蛋白｜熟鸡胸 70g｜约 115 千卡',
      '蛋白｜水煮蛋 1 个｜约 75 千卡',
      '脂肪｜南瓜子仁 12g｜约 65 千卡',
      '水果｜猕猴桃 1 个｜约 50 千卡',
      '饮品｜温开水 300mL｜约 0 千卡',
    ],
    steps: [
      '紫薯蒸熟；鸡胸撕丝与蛋同盘。',
      '南瓜子控量一把；猕猴桃保证维C。',
      '锌是养发矿物质重点，靠食物而非盲目大补剂。',
    ],
    notes: hairNotes({
      focus: '禽肉蛋白 + 食物锌 + 维C，覆盖常见微量营养薄弱点。',
      protein: '32～38g',
      calories: 440,
      keyNutrients: '锌、完整蛋白、花青素、维C',
      tip: '补锌补剂勿与食物锌叠加乱吃，长期高锌会干扰铜。',
    }),
    prepMinutes: 25,
    calories: 440,
    tags: '早餐,防脱,养发,补锌,高蛋白',
  }),
  recipe({
    templateKey: 'hair-care-bf-d4',
    title: '防脱养发｜牛肉荞麦蔬菜粥',
    mealType: '早餐',
    ingredients: [
      '主食｜荞麦米/荞麦仁 40g 煮粥｜约 140 千卡',
      '蛋白｜瘦牛里脊末 50g｜约 80 千卡',
      '蔬菜｜胡萝卜末 + 青菜 120g｜约 35 千卡',
      '蛋白｜蛋花 1 个｜约 75 千卡',
      '水果｜草莓 100g｜约 35 千卡',
      '配料｜香油极少量｜约 15 千卡',
    ],
    steps: [
      '荞麦粥煮软；牛肉末滑熟下粥。',
      '蔬菜与蛋花最后下锅，少盐少油。',
      '草莓餐后；血红素铁早餐周 1～2 次足够。',
    ],
    notes: hairNotes({
      focus: '少量红肉补铁，服务「铁储备不足可加重脱发表现」人群。',
      protein: '28～34g',
      calories: 380,
      keyNutrients: '血红素铁、锌、B12、维C（莓果）',
      tip: '已在补铁剂者，本餐可改鸡胸；茶与咖啡错开 1 小时。',
    }),
    prepMinutes: 30,
    calories: 380,
    tags: '早餐,防脱,养发,补铁,温食',
  }),
  recipe({
    templateKey: 'hair-care-bf-d5',
    title: '防脱养发｜豆腐菌菇鸡蛋羹套餐',
    mealType: '早餐',
    ingredients: [
      '蛋白｜内酯豆腐 120g｜约 60 千卡',
      '蛋白｜鸡蛋 2 个（1 蒸蛋+1 水煮或同蒸）｜约 150 千卡',
      '蔬菜｜香菇 60g + 青菜 80g｜约 35 千卡',
      '主食｜全麦馒头 1 两（50g）｜约 130 千卡',
      '水果｜苹果 1/2 个｜约 45 千卡',
      '坚果｜黑芝麻 5g｜约 30 千卡',
    ],
    steps: [
      '豆腐香菇与鸡蛋可做成蒸蛋羹或分蒸。',
      '青菜焯拌；馒头加热；黑芝麻撒在羹上。',
      '豆制品控量，当日少喝大量豆浆。',
    ],
    notes: hairNotes({
      focus: '植物+动物蛋白互补；黑芝麻提供木质素与微量矿物质（适量）。',
      protein: '30～36g',
      calories: 450,
      keyNutrients: '完整氨基酸互补、卵磷脂、钙、植物化合物',
      tip: '传说「黑芝麻生发」证据有限，当营养多样化一环即可，勿一把吃。',
    }),
    prepMinutes: 30,
    calories: 450,
    tags: '早餐,防脱,养发,高蛋白,清淡',
  }),
  recipe({
    templateKey: 'hair-care-bf-d6',
    title: '防脱养发｜酸奶奇亚籽莓果碗（周末）',
    mealType: '早餐',
    ingredients: [
      '蛋白｜无乳糖希腊酸奶 220g｜约 130 千卡',
      '谷物｜纯燕麦 30g｜约 110 千卡',
      '脂肪｜奇亚籽 10g｜约 50 千卡',
      '水果｜混合莓果 120g｜约 55 千卡',
      '脂肪｜杏仁 8g｜约 45 千卡',
      '蛋白｜水煮蛋 1 个｜约 75 千卡',
    ],
    steps: [
      '燕麦可隔夜浸泡于酸奶中，早晨加籽果与杏仁。',
      '水煮蛋另吃补完整蛋白。',
      '周末可吃慢一点，不额外果汁。',
    ],
    notes: hairNotes({
      focus: '高蛋白莓果碗，多酚与植物Ω-3，适合恢复日。',
      protein: '32～38g',
      calories: 465,
      keyNutrients: '乳蛋白、花青素、ALA、维E',
      tip: '血糖敏感者燕麦可减至 20g，蛋白别减。',
    }),
    prepMinutes: 15,
    calories: 465,
    tags: '早餐,防脱,养发,高蛋白,周末,乳糖友好',
  }),
  recipe({
    templateKey: 'hair-care-bf-d7',
    title: '防脱养发｜虾仁蔬菜鸡蛋软包',
    mealType: '早餐',
    ingredients: [
      '主食｜全麦卷饼 1 张（约 50g）｜约 130 千卡',
      '蛋白｜虾仁 60g｜约 55 千卡',
      '蛋白｜鸡蛋 1 个｜约 75 千卡',
      '蔬菜｜生菜黄瓜胡萝卜丝 120g｜约 30 千卡',
      '脂肪｜初榨橄榄油 4g｜约 35 千卡',
      '水果｜柚子瓣 100g｜约 40 千卡',
      '乳品｜无乳糖奶 150mL｜约 60 千卡',
    ],
    steps: [
      '虾仁焯水，鸡蛋煎成薄蛋皮，与蔬菜卷入全麦饼。',
      '橄榄油可刷饼或拌菜；柚子与奶搭配。',
      '虾嘌呤中等，一周 1～2 次。',
    ],
    notes: hairNotes({
      focus: '硒与优质蛋白早餐，维C来自柚子，清爽不油腻。',
      protein: '28～34g',
      calories: 425,
      keyNutrients: '硒、优质蛋白、维C、维E',
      tip: '痛风发作期虾仁改鸡胸丝 70g。',
    }),
    prepMinutes: 25,
    calories: 425,
    tags: '早餐,防脱,养发,高蛋白,清淡',
  }),
];

/* ========== 午餐 × 7 ========== */

export const HAIR_CARE_LUNCH = [
  recipe({
    templateKey: 'hair-care-lunch-d1',
    title: '防脱养发｜鸡胸糙米绿叶铁锌盘',
    mealType: '午餐',
    ingredients: [
      '主食｜糙米饭 160g｜约 180 千卡',
      '蛋白｜煎鸡胸 120g｜约 200 千卡',
      '蔬菜｜西兰花 200g｜约 70 千卡',
      '蔬菜｜清炒油麦菜 150g｜约 35 千卡',
      '脂肪｜南瓜子 8g｜约 45 千卡',
      '水果｜奇异果 1 个｜约 50 千卡',
      '汤｜番茄菌菇清汤｜约 40 千卡',
    ],
    steps: [
      '鸡胸少油煎熟；十字花科焯炒。',
      '南瓜子餐末；奇异果维C促铁。',
      '清汤少油，避免浓骨汤。',
    ],
    notes: hairNotes({
      focus: '养发午餐基本盘：充足蛋白 + 绿叶/十字花科 + 食物锌。',
      protein: '40～48g',
      calories: 620,
      keyNutrients: '完整蛋白、维C、锌、叶酸、B族',
      tip: '长期节食瘦身最伤发质；本餐不要再删鸡胸。',
    }),
    prepMinutes: 35,
    calories: 620,
    tags: '午餐,防脱,养发,高蛋白,补锌',
  }),
  recipe({
    templateKey: 'hair-care-lunch-d2',
    title: '防脱养发｜清蒸鲈鱼薯类菠菜',
    mealType: '午餐',
    ingredients: [
      '主食｜蒸土豆 200g｜约 150 千卡',
      '蛋白｜清蒸鲈鱼 110g｜约 120 千卡',
      '蔬菜｜焯水菠菜 180g｜约 40 千卡',
      '蔬菜｜凉拌木耳 70g｜约 35 千卡',
      '脂肪｜香油/橄榄油 5g｜约 45 千卡',
      '水果｜橙子 1 个｜约 70 千卡',
      '汤｜冬瓜汤｜约 25 千卡',
    ],
    steps: [
      '鲈鱼姜片清蒸；土豆整颗或切块蒸。',
      '菠菜焯水；橙与餐同食强化铁吸收。',
      '少放蒸鱼豉油糖分。',
    ],
    notes: hairNotes({
      focus: '淡水鱼优质蛋白，搭配深绿叶菜与维C，清淡利头皮油脂管理。',
      protein: '32～40g',
      calories: 485,
      keyNutrients: '优质鱼蛋白、铁、维C、钾',
      tip: '不用动物内脏「补血」，内脏维A过高反而不利。',
    }),
    prepMinutes: 35,
    calories: 485,
    tags: '午餐,防脱,养发,清淡,补铁',
  }),
  recipe({
    templateKey: 'hair-care-lunch-d3',
    title: '防脱养发｜牛里脊菠菜维C饭',
    mealType: '午餐',
    ingredients: [
      '主食｜杂粮饭 150g｜约 170 千卡',
      '蛋白｜瘦牛里脊 90g｜约 150 千卡',
      '蔬菜｜蒜蓉菠菜 200g｜约 45 千卡',
      '蔬菜｜彩椒 100g｜约 30 千卡',
      '水果｜甜椒另配或猕猴桃｜约 50 千卡',
      '脂肪｜烹调油 6g｜约 55 千卡',
      '汤｜萝卜清汤｜约 25 千卡',
    ],
    steps: [
      '牛里脊快滑至熟，忌久煮老柴。',
      '菠菜焯后炒；餐后水果维C。',
      '红肉午餐一周不超过 3 次为宜。',
    ],
    notes: hairNotes({
      focus: '血红素铁强化日，针对化验提示铁蛋白偏低的人群食物管理。',
      protein: '35～42g',
      calories: 525,
      keyNutrients: '血红素铁、锌、维C、维A前体（控量）',
      tip: '已证明缺铁者优先就医补铁，餐食是辅助不是替代。',
    }),
    prepMinutes: 30,
    calories: 525,
    tags: '午餐,防脱,养发,补铁,高蛋白',
  }),
  recipe({
    templateKey: 'hair-care-lunch-d4',
    title: '防脱养发｜藜麦鸡丝蔬菜暖沙拉',
    mealType: '午餐',
    ingredients: [
      '主食｜藜麦饭（干 60g）｜约 210 千卡',
      '蛋白｜鸡胸丝 110g｜约 180 千卡',
      '蔬菜｜樱桃番茄 150g + 黄瓜 100g + 芝麻菜｜约 50 千卡',
      '脂肪｜橄榄油 7g + 柠檬｜约 65 千卡',
      '坚果｜核桃 8g｜约 50 千卡',
      '水果｜蓝莓 50g｜约 30 千卡',
    ],
    steps: [
      '藜麦煮熟放凉；鸡丝拌入。',
      '蔬菜与橄榄油柠檬汁，核桃蓝莓铺顶。',
      '可作便当，避免美乃滋沙拉酱。',
    ],
    notes: hairNotes({
      focus: '完全蛋白谷物 + 禽肉 + 多酚核桃，抗炎与蛋白双线。',
      protein: '38～45g',
      calories: 585,
      keyNutrients: '完整蛋白、Ω-3（ALA）、花青素、镁',
      tip: '冷沙拉对胃肠弱者可改热拌温食。',
    }),
    prepMinutes: 30,
    calories: 585,
    tags: '午餐,防脱,养发,抗炎,便当',
  }),
  recipe({
    templateKey: 'hair-care-lunch-d5',
    title: '防脱养发｜豆腐鲈鱼小米碗',
    mealType: '午餐',
    ingredients: [
      '主食｜小米饭 140g｜约 160 千卡',
      '蛋白｜清蒸鲈鱼 80g｜约 90 千卡',
      '蛋白｜北豆腐 80g｜约 65 千卡',
      '蔬菜｜小白菜 200g｜约 40 千卡',
      '汤｜紫菜蛋花汤（蛋 1 个）｜约 80 千卡',
      '水果｜梨 1 个小｜约 60 千卡',
      '油脂｜烹调油 5g｜约 45 千卡',
    ],
    steps: [
      '小米煮饭；鱼与青菜清淡烹饪。',
      '豆腐适量；紫菜少量即可。',
      '整体偏低脂清淡，利脂溢性头皮护理日。',
    ],
    notes: hairNotes({
      focus: '鱼豆蛋三重蛋白，油脂克制，服务头皮出油偏多者。',
      protein: '35～42g',
      calories: 540,
      keyNutrients: '优质蛋白、碘（微量）、钾、B族',
      tip: '甲状腺疾病注意海藻碘；可去紫菜改番茄蛋汤。',
    }),
    prepMinutes: 35,
    calories: 540,
    tags: '午餐,防脱,养发,清淡,低脂',
  }),
  recipe({
    templateKey: 'hair-care-lunch-d6',
    title: '防脱养发｜火鸡胸红薯羽衣甘蓝',
    mealType: '午餐',
    ingredients: [
      '主食｜烤红薯 180g｜约 155 千卡',
      '蛋白｜火鸡胸/鸡胸 130g｜约 215 千卡',
      '蔬菜｜羽衣甘蓝或芥蓝 180g｜约 55 千卡',
      '脂肪｜橄榄油 6g｜约 55 千卡',
      '水果｜石榴籽 60g 或莓果｜约 45 千卡',
      '坚果｜杏仁 6g｜约 35 千卡',
    ],
    steps: [
      '红薯烤箱或蒸；禽肉烤熟切片。',
      '甘蓝少油快炒至断生保留脆感。',
      '石榴籽多酚收尾。',
    ],
    notes: hairNotes({
      focus: '高蛋白低碳负担午餐，深绿叶菜提供叶酸与维K等。',
      protein: '42～50g',
      calories: 560,
      keyNutrients: '完整蛋白、叶酸、β-胡萝卜素、维E、多酚',
      tip: '羽衣甘蓝买不到可改西兰花。',
    }),
    prepMinutes: 35,
    calories: 560,
    tags: '午餐,防脱,养发,高蛋白,叶酸',
  }),
  recipe({
    templateKey: 'hair-care-lunch-d7',
    title: '防脱养发｜周复盘杂粮鱼肉双拼',
    mealType: '午餐',
    ingredients: [
      '主食｜糙米燕麦饭 160g｜约 185 千卡',
      '蛋白｜清蒸鳕鱼 70g｜约 70 千卡',
      '蛋白｜鸡胸 70g｜约 115 千卡',
      '蔬菜｜什锦蔬菜 250g｜约 70 千卡',
      '脂肪｜橄榄油 5g｜约 45 千卡',
      '水果｜柑橘 1 个｜约 50 千卡',
      '汤｜菌菇清汤｜约 30 千卡',
    ],
    steps: [
      '鱼与鸡胸分蒸/煎，各一小份多样蛋白。',
      '蔬菜大火快炒；柑橘维C。',
      '周末复盘一周是否出现极端节食或酒精。',
    ],
    notes: hairNotes({
      focus: '蛋白来源多样化，降低「单一食材疲劳」并提高微量营养覆盖。',
      protein: '40～48g',
      calories: 565,
      keyNutrients: '双源优质蛋白、维C、纤维、B族',
      tip: '防脱靠长期稳定饮食+药物依从，不是周末大补一餐。',
    }),
    prepMinutes: 40,
    calories: 565,
    tags: '午餐,防脱,养发,复盘,高蛋白',
  }),
];

/* ========== 晚餐 × 7 ========== */

export const HAIR_CARE_DINNER = [
  recipe({
    templateKey: 'hair-care-dinner-d1',
    title: '防脱养发｜鸡胸小米菠菜晚粥套',
    mealType: '晚餐',
    ingredients: [
      '主食｜小米菠菜粥（小米 35g+菠菜 80g）｜约 140 千卡',
      '蛋白｜清蒸鸡胸 100g｜约 165 千卡',
      '蛋白｜蒸蛋 1 个｜约 75 千卡',
      '蔬菜｜凉拌黄瓜 120g｜约 20 千卡',
      '水果｜苹果 1/2｜约 45 千卡',
    ],
    steps: [
      '粥软烂易消化；鸡胸蒸蛋清淡。',
      '晚餐避免烧烤炸辣与酒精。',
      '吃完间隔再进行头皮用药与睡眠。',
    ],
    notes: hairNotes({
      focus: '易消化养发晚餐，服务睡眠（睡够是重要「生发疗程」）。',
      protein: '38～44g',
      calories: 445,
      keyNutrients: '完整蛋白、叶酸、铁、色氨酸相关食物组合',
      tip: '失眠勿靠夜宵重油；可温热淡饮，不喝浓茶咖啡。',
    }),
    prepMinutes: 30,
    calories: 445,
    tags: '晚餐,防脱,养发,清淡,高蛋白,助眠',
  }),
  recipe({
    templateKey: 'hair-care-dinner-d2',
    title: '防脱养发｜鳕鱼豆腐青菜汤',
    mealType: '晚餐',
    ingredients: [
      '主食｜杂粮馒头 40g 或粥 200mL｜约 100 千卡',
      '蛋白｜鳕鱼 100g｜约 100 千卡',
      '蛋白｜北豆腐 100g｜约 80 千卡',
      '蔬菜｜小白菜/油菜 200g｜约 40 千卡',
      '汤底｜清水/昆布汤 400mL｜约 15 千卡',
      '水果｜木瓜 80g｜约 30 千卡',
    ],
    steps: [
      '鱼块豆腐青菜共煮成锅，少油少盐。',
      '主食少量垫胃；木瓜餐末。',
      '油脂极低，适合头皮出油日。',
    ],
    notes: hairNotes({
      focus: '低脂高蛋白汤锅晚餐，降低高脂餐后不适与睡眠干扰。',
      protein: '35～42g',
      calories: 365,
      keyNutrients: '优质蛋白、钙、钾、水分',
      tip: '血糖低易饿者主食可加到馒头 60g。',
    }),
    prepMinutes: 30,
    calories: 365,
    tags: '晚餐,防脱,养发,低脂,清淡',
  }),
  recipe({
    templateKey: 'hair-care-dinner-d3',
    title: '防脱养发｜虾仁西兰花鸡蛋白',
    mealType: '晚餐',
    ingredients: [
      '主食｜荞麦面（干）55g｜约 185 千卡',
      '蛋白｜虾仁 70g｜约 65 千卡',
      '蛋白｜鸡蛋白（蛋清）3 个 + 全蛋 1 个｜约 120 千卡',
      '蔬菜｜西兰花 200g｜约 70 千卡',
      '油脂｜烹调油 5g｜约 45 千卡',
      '水果｜草莓 80g｜约 25 千卡',
    ],
    steps: [
      '荞麦面过水；虾仁与蛋清滑炒，西兰花同炒。',
      '控制油量；草莓补维C。',
      '训练日面条可加到 70g 干重。',
    ],
    notes: hairNotes({
      focus: '晚间仍保证蛋白落点，蛋清提高蛋白密度不过度增加蛋黄胆固醇负担。',
      protein: '40～48g',
      calories: 510,
      keyNutrients: '优质蛋白、硒、维C、硫苷',
      tip: '蛋黄全日合计建议 1～2 个即可。',
    }),
    prepMinutes: 25,
    calories: 510,
    tags: '晚餐,防脱,养发,高蛋白',
  }),
  recipe({
    templateKey: 'hair-care-dinner-d4',
    title: '防脱养发｜菌菇鸡汤蔬菜炖盅',
    mealType: '晚餐',
    ingredients: [
      '蛋白｜鸡腿去皮净肉 110g｜约 190 千卡',
      '蔬菜｜杏鲍菇香菇 150g｜约 45 千卡',
      '蔬菜｜胡萝卜白菜 200g｜约 50 千卡',
      '主食｜糙米饭 100g｜约 115 千卡',
      '汤｜原汤去浮油｜约 30 千卡',
      '水果｜猕猴桃 1 个｜约 50 千卡',
    ],
    steps: [
      '鸡块焯水后与菌菇蔬菜小火炖，全程去皮去浮油。',
      '喝汤吃肉菜，主食适量。',
      '不做浓白高油火锅汤底。',
    ],
    notes: hairNotes({
      focus: '温暖汤食提升依从性；去皮控脂，蛋白仍足。',
      protein: '32～38g',
      calories: 480,
      keyNutrients: '完整蛋白、B族、β-胡萝卜素、维C',
      tip: '汤不是越浓白越补，浮油撇掉更合适皮脂管理。',
    }),
    prepMinutes: 45,
    calories: 480,
    tags: '晚餐,防脱,养发,汤品,清淡',
  }),
  recipe({
    templateKey: 'hair-care-dinner-d5',
    title: '防脱养发｜三文鱼芦笋藜麦',
    mealType: '晚餐',
    ingredients: [
      '主食｜藜麦 50g（干）｜约 180 千卡',
      '蛋白｜三文鱼 80g｜约 160 千卡',
      '蔬菜｜芦笋 180g｜约 40 千卡',
      '蔬菜｜生菜沙拉 80g｜约 15 千卡',
      '脂肪｜橄榄油 5g｜约 45 千卡',
      '乳品｜无乳糖酸奶 80g｜约 45 千卡',
    ],
    steps: [
      '三文鱼少油煎或蒸；芦笋焯/烤。',
      '藜麦装盘；酸奶可作酱。',
      'Ω-3 晚餐有助兼顾心血管与头皮微炎症管理。',
    ],
    notes: hairNotes({
      focus: '晚间Ω-3 强化餐，蛋白来自鱼与藜麦。',
      protein: '30～36g',
      calories: 485,
      keyNutrients: 'EPA/DHA、优质蛋白、维D（鱼）、叶酸',
      tip: '用药前后洗手，避免鱼油沾染头皮用药区。',
    }),
    prepMinutes: 30,
    calories: 485,
    tags: '晚餐,防脱,养发,Ω-3,抗炎',
  }),
  recipe({
    templateKey: 'hair-care-dinner-d6',
    title: '防脱养发｜豆腐蔬菜蛋奶羹（周末）',
    mealType: '晚餐',
    ingredients: [
      '蛋白｜内酯豆腐 150g｜约 75 千卡',
      '蛋白｜鸡蛋 1.5 个蒸蛋｜约 110 千卡',
      '蛋白｜无乳糖奶 100mL 入蛋羹｜约 40 千卡',
      '蔬菜｜菠菜南瓜丁 200g｜约 55 千卡',
      '主食｜软米饭 100g｜约 115 千卡',
      '水果｜香蕉 1/2 根｜约 45 千卡',
    ],
    steps: [
      '豆腐蛋奶同蒸至凝固；蔬菜另焯或蒸。',
      '口感软、负担小，适合周末放松但不少蛋白。',
      '香蕉钾含量高，可助训练后恢复。',
    ],
    notes: hairNotes({
      focus: '精细软食不等于营养差，照样锁住蛋白与维矿。',
      protein: '28～34g',
      calories: 440,
      keyNutrients: '乳清/卵蛋白、钙、钾、叶酸',
      tip: '乳糖不耐受务必无乳糖奶；可改清水蛋羹+酸奶另行。',
    }),
    prepMinutes: 30,
    calories: 440,
    tags: '晚餐,防脱,养发,周末,乳糖友好',
  }),
  recipe({
    templateKey: 'hair-care-dinner-d7',
    title: '防脱养发｜烤鸡胸沙拉橙香收官',
    mealType: '晚餐',
    ingredients: [
      '蛋白｜烤鸡胸 120g｜约 200 千卡',
      '主食｜全麦面包 1 片或薯角 100g｜约 90 千卡',
      '蔬菜｜混合沙拉菜 150g + 番茄黄瓜｜约 40 千卡',
      '水果｜橙肉 120g（拌入沙拉）｜约 50 千卡',
      '脂肪｜橄榄油 6g｜约 55 千卡',
      '坚果｜核桃 6g｜约 40 千卡',
    ],
    steps: [
      '鸡胸烤熟切丁拌沙拉，橙肉与橄榄油黑胡椒。',
      '主食少量；核桃控量。',
      '复盘：本周是否戒酒、是否规律用药、是否睡够 7 小时。',
    ],
    notes: hairNotes({
      focus: '一周收官清爽盘：蛋白+维C+少量Ω-3坚果。',
      protein: '38～44g',
      calories: 475,
      keyNutrients: '完整蛋白、维C、ALA、纤维',
      tip: '防脱是疗程思维：下周继续稳定饮食，比单次「生发秘方餐」重要。',
    }),
    prepMinutes: 30,
    calories: 475,
    tags: '晚餐,防脱,养发,复盘,高蛋白,清淡',
  }),
];

export const HAIR_CARE_RECIPES = [
  ...HAIR_CARE_BREAKFAST,
  ...HAIR_CARE_LUNCH,
  ...HAIR_CARE_DINNER,
];
