/**
 * 系统菜谱库（午餐 / 晚餐 / 加餐）
 *
 * 定位：先沉淀「适合吃的菜」供浏览与筛选；「按 7 天怎么排」留给后续定制板块。
 *
 * 原则：
 * - 营养均衡：主食 + 优质蛋白 + 蔬菜（可选汤/水果）；
 * - 低嘌呤友好：少内脏/浓汤/大量海鲜，豆类不过量；
 * - 养发营养支持：优质蛋白、蔬果维生素与适量健康脂肪；
 * - 默认乳糖友好：尽量无乳制品，或可用无乳糖替代；
 * - 热量按分菜估算，calories 为整餐合计。
 *
 * 食材行格式：类别｜菜品与用量｜约 N 千卡
 */

function dishes(lines) {
  return lines.join('\n');
}

function mealNotes({ focus, protein, calories, tip, nutrients, effects }) {
  return [
    `功效：${focus}`,
    `补什么：${nutrients || `优质蛋白约 ${protein}，以及蔬果维生素、矿物质与膳食纤维`}`,
    `作用：${effects || '支持日常能量与饱腹感，兼顾尿酸友好与毛囊营养支持，减少高糖零食依赖。'}`,
    `营养：优质蛋白约 ${protein}；参考热量约 ${calories} 千卡/餐。`,
    tip ? `贴士：${tip}` : null,
    '说明：有利于尿酸管理与养发营养支持，不等于治疗高尿酸或脱发；特殊病情请遵医嘱。',
  ].filter(Boolean).join('\n');
}

function recipe(def) {
  return {
    prepMinutes: 30,
    tags: '',
    ...def,
    ingredients: Array.isArray(def.ingredients) ? dishes(def.ingredients) : def.ingredients,
    steps: Array.isArray(def.steps) ? def.steps.join('\n') : def.steps,
  };
}

/** 干净增肌午餐周轮换（lunch-d1～d7）；对齐 docs/md/文字.txt，目标约 450～550 千卡 */
export const LUNCH_RECIPES = [
  recipe({
    templateKey: 'lunch-d1',
    title: '鸡胸糙米西兰花盘',
    mealType: '午餐',
    ingredients: [
      '主食｜糙米饭 140g（约大半碗）｜约 160 千卡',
      '蛋白｜清蒸鸡胸肉 110g｜约 180 千卡',
      '蔬菜｜蒜蓉西兰花 200g｜约 70 千卡',
      '蔬菜｜凉拌黄瓜 100g｜约 15 千卡',
      '油脂｜橄榄油 3g｜约 25 千卡',
      '饮品｜温开水｜约 0 千卡',
    ],
    steps: [
      '糙米提前浸泡，按约 1:1.2 米水比煮熟。',
      '鸡胸洗净少盐蒸 12～15 分钟至断生，切片。',
      '西兰花焯水后蒜末少油快炒；黄瓜凉拌少盐不放糖。',
      '全餐不加油炸酱汁与含糖饮料。',
    ],
    notes: mealNotes({
      focus: '干净增肌基础款：全谷物 + 去皮禽肉 + 西兰花纤维。',
      protein: '35～40g',
      calories: 450,
      tip: '不喝浓肉汤；油量严格控在 3g 左右。',
      nutrients: '优质蛋白、复合碳水与十字花科纤维，尿酸负担低',
      effects: '支撑上午训练后的补能，减少垃圾食品依赖。',
    }),
    prepMinutes: 35,
    calories: 450,
    tags: '午餐,干净饮食,增肌控脂,尿酸友好,高蛋白,全谷物',
  }),
  recipe({
    templateKey: 'lunch-d2',
    title: '白米饭家常小炒盘',
    mealType: '午餐',
    ingredients: [
      '主食｜白米饭 120g（约大半碗，生米约 40～45g）｜约 140 千卡',
      '蛋白｜柠檬鸡爪 35g（约 2～3 小只）｜约 70 千卡',
      '蛋白｜肉末蒸蛋 85g（肉末约 15～20g + 蛋液）｜约 100 千卡',
      '蔬菜｜素炒丝瓜 130g（熟重）｜约 50 千卡',
      '蔬菜｜花菜炒瘦肉 90g（花菜约 60g + 瘦肉约 28g）｜约 80 千卡',
      '汤品｜紫菜煲 280mL（清汤，紫菜干约 2～3g）｜约 30 千卡',
      '蔬菜｜大黄瓜炒瘦肉 90g（黄瓜约 60g + 瘦肉约 28g）｜约 75 千卡',
    ],
    steps: [
      '白米饭控量约 120g，全餐炒菜合计用油约 5～8g。',
      '柠檬鸡爪只作开胃小碟（嘌呤偏高），约 2～3 小只。',
      '肉末蒸蛋：肉末 15～20g 入蛋液蒸至刚好凝固。',
      '素炒丝瓜少油快炒；花菜与大黄瓜两道瘦肉合计生重约 50～60g。',
      '紫菜煲清汤，不熬浓、不多油。',
    ],
    notes: mealNotes({
      focus: '家常小炒拼盘：米饭稳碳水，蒸蛋+控量瘦肉补蛋白，丝瓜黄瓜花菜拉纤维。',
      protein: '30～38g',
      calories: 520,
      tip: '鸡爪嘌呤偏高，尿酸不稳时可去掉，把米饭提到 140g 或蒸蛋提到 100g。两道炒肉瘦肉合计别超过 60g。',
      nutrients: '优质蛋白、淀粉碳水与大量瓜菜纤维',
      effects: '落在午餐约 500～545 千卡目标内，家常好执行。',
    }),
    prepMinutes: 40,
    calories: 520,
    tags: '午餐,干净饮食,增肌控脂,家常,控油',
  }),
  recipe({
    templateKey: 'lunch-d3',
    title: '虾仁糙米西兰花盘',
    mealType: '午餐',
    ingredients: [
      '主食｜糙米饭 160g｜约 180 千卡',
      '蛋白｜白灼大虾仁 90g（控量）｜约 95 千卡',
      '蛋白｜水煮蛋清 1 个｜约 20 千卡',
      '蔬菜｜蒜蓉西兰花 220g｜约 75 千卡',
      '蔬菜｜凉拌黄瓜 120g｜约 20 千卡',
      '油脂｜橄榄油 3g｜约 25 千卡',
      '汤品｜番茄清汤 250mL｜约 35 千卡',
    ],
    steps: [
      '糙米煮熟；虾仁焯水至变色即捞出，不油炸。',
      '蛋清煮熟切片；西兰花蒜蓉少油炒；黄瓜凉拌。',
      '番茄清水煮汤，少盐。',
      '海鲜控在 90g，不另加贝类或浓海鲜汤。',
    ],
    notes: mealNotes({
      focus: '控量虾仁 + 蛋清补蛋白，糙米稳能量，尿酸友好优先控海鲜。',
      protein: '32～38g',
      calories: 450,
      tip: '尿酸偏高时虾仁改鸡胸 100g，去掉蛋清也可。',
      nutrients: '优质蛋白、全谷物与蔬菜纤维',
      effects: '干净增肌轮换日，避免酱汁与油炸海鲜。',
    }),
    prepMinutes: 30,
    calories: 450,
    tags: '午餐,干净饮食,增肌控脂,尿酸友好,控量海鲜',
  }),
  recipe({
    templateKey: 'lunch-d4',
    title: '瘦牛荞麦西兰花碗',
    mealType: '午餐',
    ingredients: [
      '主食｜荞麦面（干）50g 煮熟｜约 170 千卡',
      '蛋白｜香煎瘦牛肉丝 90g（去肥油）｜约 150 千卡',
      '蔬菜｜清炒西兰花 200g｜约 70 千卡',
      '蔬菜｜清炒青菜 150g｜约 30 千卡',
      '调味｜生抽少许 + 橄榄油 3g｜约 30 千卡',
      '汤品｜萝卜丝清汤 250mL｜约 25 千卡',
    ],
    steps: [
      '荞麦面煮熟过凉；瘦牛肉去肥油切丝，少油快炒断生。',
      '西兰花与青菜少油清炒；萝卜丝清水煮汤。',
      '不裹淀粉油炸，不用甜面酱或浓黑椒汁。',
    ],
    notes: mealNotes({
      focus: '瘦牛肉补铁与蛋白，荞麦稳碳水，干净少油。',
      protein: '35～40g',
      calories: 475,
      tip: '选里脊/腱子瘦切，弃肥边；一周牛肉限此一天即可。',
      nutrients: '优质蛋白、铁、复合碳水与绿叶纤维',
      effects: '支撑力量训练日中午补能，避免油腻红肉。',
    }),
    prepMinutes: 35,
    calories: 475,
    tags: '午餐,干净饮食,增肌控脂,高蛋白,荞麦',
  }),
  recipe({
    templateKey: 'lunch-d5',
    title: '鸡胸糙米高蛋白盘',
    mealType: '午餐',
    ingredients: [
      '主食｜糙米饭 150g｜约 170 千卡',
      '蛋白｜香煎鸡胸肉 120g｜约 200 千卡',
      '蔬菜｜清炒西兰花 200g｜约 70 千卡',
      '蔬菜｜番茄黄瓜沙拉 150g（无酱）｜约 30 千卡',
      '油脂｜橄榄油 3g｜约 25 千卡',
      '饮品｜温开水｜约 0 千卡',
    ],
    steps: [
      '糙米煮熟；鸡胸厚片少油煎至熟透切片。',
      '西兰花焯水少油炒；番茄黄瓜洗净无酱拌匀。',
      '训练日可把力量课安排在餐后 1.5～2 小时。',
    ],
    notes: mealNotes({
      focus: '训练日高蛋白干净午餐：鸡胸 + 糙米 + 西兰花。',
      protein: '40～45g',
      calories: 495,
      tip: '不额外加坚果酱或含糖酱料；练前香蕉走夜宵/练前任务。',
      nutrients: '更高优质蛋白、全谷物与十字花科纤维',
      effects: '支持肌肉与毛发角蛋白合成，卡控在午餐目标内。',
    }),
    prepMinutes: 30,
    calories: 495,
    tags: '午餐,干净饮食,增肌控脂,高蛋白,训练日',
  }),
  recipe({
    templateKey: 'lunch-d6',
    title: '鸡胸荞麦清淡碗',
    mealType: '午餐',
    ingredients: [
      '主食｜荞麦面（干）55g 煮熟｜约 185 千卡',
      '蛋白｜水煮鸡胸丝 100g｜约 165 千卡',
      '蔬菜｜西兰花 + 胡萝卜丝 220g｜约 75 千卡',
      '汤底｜昆布/菌菇清汤 300mL｜约 25 千卡',
      '调味｜生抽少许 + 香油 2g｜约 20 千卡',
      '蔬菜｜凉拌黄瓜 80g｜约 15 千卡',
    ],
    steps: [
      '荞麦面煮熟过凉；鸡胸清水煮熟撕丝。',
      '西兰花胡萝卜焯水或少油快炒，与面、鸡丝入碗。',
      '倒入温热清汤，少许生抽香油，不加油炸酱料。',
    ],
    notes: mealNotes({
      focus: '恢复日清淡增肌：荞麦 + 鸡胸 + 大量蔬菜。',
      protein: '35～40g',
      calories: 485,
      tip: '汤底避免浓骨汤与内脏汤。',
      nutrients: '优质蛋白、荞麦纤维与多彩蔬菜',
      effects: '轻负担补能，适合周末或恢复日。',
    }),
    prepMinutes: 30,
    calories: 485,
    tags: '午餐,干净饮食,增肌控脂,尿酸友好,荞麦',
  }),
  recipe({
    templateKey: 'lunch-d7',
    title: '鲈鱼糙米西兰花盘',
    mealType: '午餐',
    ingredients: [
      '主食｜糙米饭 140g｜约 160 千卡',
      '蛋白｜清蒸鲈鱼 110g｜约 120 千卡',
      '蔬菜｜清炒西兰花 200g｜约 70 千卡',
      '蔬菜｜清炒时蔬 150g（青菜/彩椒）｜约 40 千卡',
      '油脂｜橄榄油 3g｜约 25 千卡',
      '汤品｜番茄金针菇清汤｜约 40 千卡',
    ],
    steps: [
      '糙米煮熟；鲈鱼姜片清蒸，不淋大量油。',
      '西兰花与时蔬少油快炒；番茄金针菇煮清汤。',
      '不喝含糖饮料，外食优先清蒸白灼。',
    ],
    notes: mealNotes({
      focus: '周日收尾：淡水鱼 + 糙米 + 西兰花，干净均衡。',
      protein: '32～38g',
      calories: 455,
      tip: '外食避开火锅内脏与油炸拼盘。',
      nutrients: '优质蛋白、全谷物、维 C 与膳食纤维',
      effects: '一周干净饮食收尾，尿酸友好且易执行。',
    }),
    prepMinutes: 35,
    calories: 455,
    tags: '午餐,干净饮食,增肌控脂,尿酸友好,淡水鱼',
  }),
  recipe({
    templateKey: 'lunch-turkey-quinoa',
    title: '火鸡胸藜麦时蔬碗',
    mealType: '午餐',
    ingredients: [
      '主食｜藜麦饭 140g｜约 170 千卡',
      '蛋白｜烤火鸡胸 100g｜约 135 千卡',
      '蔬菜｜清炒芦笋 150g｜约 35 千卡',
      '蔬菜｜番茄黄瓜沙拉 150g｜约 35 千卡',
      '汤品｜菌菇清汤｜约 40 千卡',
      '水果｜橙子半个｜约 35 千卡',
    ],
    steps: [
      '藜麦淘洗后按包装比例煮熟。',
      '火鸡胸少盐烤箱 180℃ 烤约 18 分钟，切片。',
      '芦笋焯水少油快炒；番茄黄瓜切块凉拌。',
      '菌菇清水煮汤少盐。',
      '橙子半个作餐后水果。',
    ],
    notes: mealNotes({
      focus: '去皮禽肉 + 藜麦，蛋白质量好，嘌呤负担相对可控。',
      protein: '35～40g',
      calories: 450,
      tip: '买不到火鸡可用鸡胸替代同等分量。',
    }),
    prepMinutes: 35,
    calories: 450,
    tags: '午餐,高蛋白,养发,尿酸友好,全谷物',
  }),
  recipe({
    templateKey: 'lunch-shrimp-veggie',
    title: '少量虾仁杂粮蔬菜盅',
    mealType: '午餐',
    ingredients: [
      '主食｜糙米饭 130g｜约 145 千卡',
      '蛋白｜清炒虾仁 60g（适量）｜约 55 千卡',
      '蛋白｜水煮蛋 1 个｜约 75 千卡',
      '蔬菜｜西葫芦胡萝卜炒 200g｜约 50 千卡',
      '蔬菜｜白灼菠菜 150g｜约 30 千卡',
      '汤品｜番茄蛋花汤（半个蛋量已计入蛋）｜约 40 千卡',
      '水果｜苹果半个｜约 45 千卡',
    ],
    steps: [
      '糙米煮熟。',
      '虾仁解冻洗净，少油快炒至变色即出锅（严格控量）。',
      '蔬菜分别清炒/白灼；番茄汤简单煮开。',
      '鸡蛋煮熟；苹果半个。',
      '海鲜总量控制，不叠加螃蟹贝类。',
    ],
    notes: mealNotes({
      focus: '虾仁少量搭配鸡蛋补蛋白；海鲜不过量，尿酸更友好。',
      protein: '28～33g',
      calories: 440,
      tip: '痛风急性期去掉虾仁，改鸡胸 80g。',
    }),
    prepMinutes: 30,
    calories: 440,
    tags: '午餐,尿酸友好,养发,控海鲜',
  }),
  recipe({
    templateKey: 'lunch-egg-potato-bowl',
    title: '双蛋土豆时蔬饱腹盘',
    mealType: '午餐',
    ingredients: [
      '主食｜蒸土豆 200g｜约 150 千卡',
      '蛋白｜水煮蛋 2 个｜约 150 千卡',
      '蔬菜｜清炒西兰花 180g｜约 60 千卡',
      '蔬菜｜凉拌黄瓜木耳 150g｜约 45 千卡',
      '汤品｜紫菜汤｜约 15 千卡',
      '水果｜猕猴桃 1 个｜约 50 千卡',
      '油脂｜橄榄油 3g｜约 25 千卡',
    ],
    steps: [
      '土豆带皮或去皮蒸熟。',
      '鸡蛋冷水下锅煮 8～10 分钟。',
      '西兰花蒜蓉少油炒；黄瓜木耳凉拌。',
      '紫菜汤少盐；猕猴桃去皮。',
      '无红肉无海鲜的素蛋白午餐选项。',
    ],
    notes: mealNotes({
      focus: '以蛋为蛋白核心，薯类饱腹，适合不想吃肉的日子。',
      protein: '20～25g',
      calories: 495,
      tip: '若需更高蛋白，可再加鸡胸 50g。',
    }),
    prepMinutes: 25,
    calories: 495,
    tags: '午餐,鸡蛋,尿酸友好,养发,少油',
  }),
  recipe({
    templateKey: 'lunch-chicken-salad',
    title: '鸡胸全麦吐司沙拉午餐',
    mealType: '午餐',
    ingredients: [
      '主食｜全麦吐司 2 片（约 55g）｜约 140 千卡',
      '蛋白｜即食/蒸鸡胸 110g｜约 180 千卡',
      '蔬菜｜混合生菜沙拉 200g｜约 30 千卡',
      '蔬菜｜樱桃番茄 100g｜约 20 千卡',
      '油脂｜橄榄油 5g + 柠檬汁｜约 45 千卡',
      '水果｜蓝莓 60g｜约 35 千卡',
    ],
    steps: [
      '吐司微烤；鸡胸撕丝或切片。',
      '生菜番茄洗净沥干，淋橄榄油与柠檬汁拌匀。',
      '鸡胸铺在沙拉上，吐司另放或切条。',
      '蓝莓餐末食用。',
      '不使用蛋黄酱、千岛酱等重油酱料。',
    ],
    notes: mealNotes({
      focus: '轻便可外带的午餐结构：全麦 + 鸡胸 + 生蔬。',
      protein: '35～40g',
      calories: 450,
      tip: '办公室可用便携鸡胸与即食沙拉简化步骤。',
    }),
    prepMinutes: 15,
    calories: 450,
    tags: '午餐,高蛋白,快手,养发,尿酸友好',
  }),
  recipe({
    templateKey: 'lunch-corn-chicken-soup',
    title: '玉米鸡胸蔬菜汤饭',
    mealType: '午餐',
    ingredients: [
      '主食｜软米饭 120g｜约 140 千卡',
      '蛋白｜鸡胸块 90g｜约 150 千卡',
      '主食｜甜玉米粒 80g｜约 70 千卡',
      '蔬菜｜胡萝卜青菜 200g｜约 45 千卡',
      '汤品｜清鸡汤（去油，非浓骨汤）300mL｜约 40 千卡',
      '水果｜梨半个｜约 40 千卡',
    ],
    steps: [
      '鸡胸焯水后与玉米、胡萝卜加水慢煮 15 分钟，撇去浮油。',
      '青菜最后下锅烫熟；米饭另盛。',
      '汤宜清淡，不放内脏与油渣。',
      '梨半个。',
    ],
    notes: mealNotes({
      focus: '汤饭一体、好消化，适合胃口一般或需要温热餐的时候。',
      protein: '28～32g',
      calories: 485,
      tip: '务必去浮油；不要改成浓高汤。',
    }),
    prepMinutes: 35,
    calories: 485,
    tags: '午餐,汤饭,尿酸友好,养发',
  }),
];

export const DINNER_RECIPES = [
  recipe({
    templateKey: 'dinner-d1',
    title: '豆腐蛋羹杂粮轻食',
    mealType: '晚餐',
    ingredients: [
      '主食｜小米粥 250mL｜约 120 千卡',
      '蛋白｜蒸蛋羹（鸡蛋 1.5 个）｜约 110 千卡',
      '蛋白｜内酯豆腐 100g｜约 50 千卡',
      '蔬菜｜清炒上海青 200g｜约 40 千卡',
      '蔬菜｜凉拌番茄 150g｜约 30 千卡',
      '水果｜苹果 1/2 个（约 90g）｜约 50 千卡',
    ],
    steps: [
      '小米煮粥至软糯。',
      '鸡蛋加温水 1:1.5 搅匀过筛蒸 10 分钟成蛋羹。',
      '豆腐切块上锅蒸 5 分钟，淋少许生抽。',
      '上海青少油清炒；番茄切块凉拌少盐。',
      '晚餐宜早，睡前 2～3 小时结束进食。',
    ],
    notes: mealNotes({
      focus: '蛋 + 少量豆腐补蛋白，清淡易消化。',
      protein: '22～28g',
      calories: 400,
      tip: '豆腐已控量；勿叠加豆浆黄豆大餐。',
    }),
    prepMinutes: 30,
    calories: 400,
    tags: '晚餐,清淡,尿酸友好,养发,乳糖友好',
  }),
  recipe({
    templateKey: 'dinner-d2',
    title: '瘦牛肉菌菇时蔬',
    mealType: '晚餐',
    ingredients: [
      '主食｜全麦馒头 60g（约半个）｜约 140 千卡',
      '蛋白｜快炒瘦牛肉丝 60g｜约 100 千卡',
      '蔬菜｜杏鲍菇青椒炒 200g｜约 70 千卡',
      '蔬菜｜清炒白菜 200g｜约 35 千卡',
      '汤品｜丝瓜蛋汤（半个蛋）｜约 60 千卡',
      '水果｜奇异果 1 个｜约 50 千卡',
    ],
    steps: [
      '牛肉丝用少许淀粉抓匀，热锅少油快炒断生即出锅（控量 60g）。',
      '杏鲍菇青椒少油炒香；白菜清炒。',
      '丝瓜煮汤，淋入半个蛋花。',
      '全麦馒头蒸热；猕猴桃洗净。',
      '红肉全天不重复大量食用。',
    ],
    notes: mealNotes({
      focus: '少量瘦牛肉提供铁与蛋白；严格控量降嘌呤风险。',
      protein: '25～30g',
      calories: 455,
      tip: '痛风发作期把牛肉换成鸡蛋 2 个或鸡胸 80g。',
    }),
    prepMinutes: 30,
    calories: 455,
    tags: '晚餐,少量红肉,养发,尿酸友好',
  }),
  recipe({
    templateKey: 'dinner-d3',
    title: '豆腐蛋蔬菜汤面',
    mealType: '晚餐',
    ingredients: [
      '主食｜龙须面/挂面（干）50g｜约 175 千卡',
      '蛋白｜北豆腐 60g｜约 50 千卡',
      '蛋白｜鸡蛋 1 个｜约 75 千卡',
      '蔬菜｜青菜胡萝卜入汤 200g｜约 40 千卡',
      '汤底｜番茄蔬菜汤｜约 40 千卡',
      '水果｜樱桃 80g｜约 40 千卡',
    ],
    steps: [
      '番茄蔬菜汤烧开，下面条煮至软韧。',
      '豆腐切小块入汤；鸡蛋可卧蛋或打散成蛋花。',
      '青菜胡萝卜最后下锅烫熟。',
      '少盐少油，不浇炸酱。',
      '樱桃洗净作餐后水果。',
    ],
    notes: mealNotes({
      focus: '易消化汤面，豆腐控量，蛋白由蛋补足。',
      protein: '22～28g',
      calories: 420,
      tip: '面条分量不宜再加，避免夜间过高碳水。',
    }),
    prepMinutes: 25,
    calories: 420,
    tags: '晚餐,汤面,尿酸友好,养发',
  }),
  recipe({
    templateKey: 'dinner-d4',
    title: '土豆泥全麦卷蔬菜',
    mealType: '晚餐',
    ingredients: [
      '主食｜土豆泥（土豆 180g，少油）｜约 150 千卡',
      '主食｜全麦卷饼 1/2 张（约 35g）｜约 90 千卡',
      '蛋白｜煎蛋 1 个｜约 90 千卡',
      '蔬菜｜生菜黄瓜番茄卷菜 150g｜约 30 千卡',
      '蔬菜｜清炒茄子少油 120g｜约 50 千卡',
      '汤品｜紫菜汤｜约 15 千卡',
      '水果｜橙子半个｜约 35 千卡',
    ],
    steps: [
      '土豆蒸软捣成泥，可加少许温水调稀，不加油炸。',
      '鸡蛋少油煎熟；全麦饼加热后卷生菜黄瓜番茄。',
      '茄子少油快炒。',
      '紫菜汤简单煮开少盐。',
      '橙子半个收尾。',
    ],
    notes: mealNotes({
      focus: '薯类主食 + 蛋蛋白 + 大量生熟蔬菜。',
      protein: '18～22g',
      calories: 460,
      tip: '茄子吸油，务必少油快炒。',
    }),
    prepMinutes: 30,
    calories: 460,
    tags: '晚餐,少油,尿酸友好,养发',
  }),
  recipe({
    templateKey: 'dinner-d5',
    title: '清蒸龙利鱼大量蔬菜',
    mealType: '晚餐',
    ingredients: [
      '主食｜糙米饭 100g｜约 115 千卡',
      '蛋白｜清蒸龙利鱼/巴沙鱼 90g｜约 80 千卡',
      '蔬菜｜白灼菜心 200g｜约 35 千卡',
      '蔬菜｜凉拌海带丝（淡）80g｜约 30 千卡',
      '汤品｜黄瓜蛋花汤｜约 55 千卡',
      '水果｜草莓 100g｜约 35 千卡',
      '调味｜蒸鱼料汁极少量｜约 15 千卡',
    ],
    steps: [
      '糙米饭煮好；鱼肉洗净姜片蒸 6～8 分钟。',
      '菜心白灼；海带丝焯水凉拌少盐（不麻辣重油）。',
      '黄瓜蛋花汤少油少盐。',
      '以清淡易消化为主，便于睡眠。',
      '鱼类仍控制单次分量，不吃鱼籽内脏。',
    ],
    notes: mealNotes({
      focus: '白鱼嘌呤相对可控且易消化，配大量蔬菜。',
      protein: '28～32g',
      calories: 365,
      tip: '急性痛风期改鸡胸或鸡蛋，暂停鱼类。',
    }),
    prepMinutes: 30,
    calories: 365,
    tags: '晚餐,清淡,尿酸友好,养发',
  }),
  recipe({
    templateKey: 'dinner-d6',
    title: '蔬菜蛋花汤配杂粮粥',
    mealType: '晚餐',
    ingredients: [
      '主食｜燕麦杂粮粥 300mL｜约 150 千卡',
      '蛋白｜水煮蛋 1 个｜约 75 千卡',
      '蛋白｜鸡胸丝 50g｜约 80 千卡',
      '蔬菜｜大白菜炖豆腐少量（豆腐 40g）｜约 70 千卡',
      '汤品｜蔬菜清汤｜约 25 千卡',
      '水果｜梨半个｜约 40 千卡',
    ],
    steps: [
      '燕麦与少许糙米煮粥。',
      '鸡蛋煮熟；鸡胸丝焯水或少油炒熟。',
      '大白菜与小块豆腐炖软，少油。',
      '另备一碗清汤蔬菜。',
      '宜早吃，保证睡眠。',
    ],
    notes: mealNotes({
      focus: '粥品温和，蛋白分散来源，豆腐严格少量。',
      protein: '25～30g',
      calories: 440,
      tip: '不喝酒精，不吃火锅。',
    }),
    prepMinutes: 35,
    calories: 440,
    tags: '晚餐,清淡,尿酸友好',
  }),
  recipe({
    templateKey: 'dinner-d7',
    title: '杂粮面素菜蛋白碗',
    mealType: '晚餐',
    ingredients: [
      '主食｜荞麦面（干）55g｜约 190 千卡',
      '蛋白｜茶香蛋 1 个｜约 75 千卡',
      '蛋白｜焯水面鸡胸 60g｜约 100 千卡',
      '蔬菜｜黄瓜丝豆芽菜 200g｜约 40 千卡',
      '汤底｜清汤｜约 15 千卡',
      '水果｜蓝莓 60g｜约 35 千卡',
      '调味｜香油 2g｜约 20 千卡',
    ],
    steps: [
      '荞麦面煮熟过凉。',
      '鸡胸焯水切片；鸡蛋可提前卤/煮。',
      '黄瓜丝、豆芽焯水凉拌。',
      '清汤少许香油调味装碗。',
      '避免烧烤炸串。',
    ],
    notes: mealNotes({
      focus: '杂粮面 + 双蛋白，纤维充足。',
      protein: '28～33g',
      calories: 475,
      tip: '豆芽适量；不要豆芽加油条等油炸组合。',
    }),
    prepMinutes: 30,
    calories: 475,
    tags: '晚餐,养发,尿酸友好,荞麦',
  }),
  recipe({
    templateKey: 'dinner-steam-egg-veg',
    title: '双菇蒸蛋青菜晚餐',
    mealType: '晚餐',
    ingredients: [
      '主食｜杂粮饭 110g｜约 125 千卡',
      '蛋白｜香菇肉末蒸蛋（鸡蛋 2 个，无肉末或极少量瘦肉）｜约 160 千卡',
      '蔬菜｜清炒油麦菜 200g｜约 35 千卡',
      '蔬菜｜凉拌黄瓜 120g｜约 20 千卡',
      '汤品｜番茄豆腐汤（豆腐 40g）｜约 55 千卡',
      '水果｜草莓 80g｜约 30 千卡',
    ],
    steps: [
      '鸡蛋加温水搅匀，铺香菇片蒸 12 分钟（可不放肉末）。',
      '杂粮饭加热；油麦菜少油清炒。',
      '番茄豆腐汤少油少盐。',
      '黄瓜凉拌；草莓洗净。',
    ],
    notes: mealNotes({
      focus: '以蛋为主蛋白的清淡晚餐，菌菇增鲜少油。',
      protein: '22～28g',
      calories: 425,
      tip: '若加瘦肉末，总量控制在 20g 以内。',
    }),
    prepMinutes: 30,
    calories: 425,
    tags: '晚餐,清淡,鸡蛋,尿酸友好,养发',
  }),
  recipe({
    templateKey: 'dinner-chicken-lettuce',
    title: '鸡胸生菜包轻晚餐',
    mealType: '晚餐',
    ingredients: [
      '主食｜蒸玉米 100g｜约 90 千卡',
      '蛋白｜煎鸡胸丁 100g｜约 165 千卡',
      '蔬菜｜生菜叶 8～10 片｜约 15 千卡',
      '蔬菜｜彩椒丁洋葱丁 100g｜约 30 千卡',
      '汤品｜冬瓜清汤｜约 25 千卡',
      '水果｜猕猴桃 1 个｜约 50 千卡',
      '调味｜生抽少许｜约 10 千卡',
    ],
    steps: [
      '鸡胸丁少油煎熟，与彩椒洋葱同炒断生。',
      '用生菜叶包裹食用；玉米另配。',
      '冬瓜清汤少盐。',
      '猕猴桃餐后。',
      '不放甜面酱、沙拉酱。',
    ],
    notes: mealNotes({
      focus: '低碳水倾向的轻晚餐，蛋白充足、蔬菜量大。',
      protein: '32～36g',
      calories: 385,
      tip: '若白天运动量大，可加半碗糙米饭。',
    }),
    prepMinutes: 25,
    calories: 385,
    tags: '晚餐,高蛋白,轻食,尿酸友好,养发',
  }),
  recipe({
    templateKey: 'dinner-yam-egg',
    title: '山药鸡蛋青菜暖胃餐',
    mealType: '晚餐',
    ingredients: [
      '主食｜清炒山药 150g｜约 90 千卡',
      '主食｜小米粥 200mL｜约 95 千卡',
      '蛋白｜炒蛋/蒸蛋 1.5 个｜约 110 千卡',
      '蔬菜｜清炒菠菜 200g｜约 40 千卡',
      '蔬菜｜凉拌番茄 120g｜约 25 千卡',
      '水果｜梨半个｜约 40 千卡',
    ],
    steps: [
      '山药去皮切段焯水后少油快炒。',
      '小米煮粥；鸡蛋蒸或少油炒。',
      '菠菜清炒；番茄凉拌。',
      '梨半个。',
      '避免油炸山药片。',
    ],
    notes: mealNotes({
      focus: '温热易消化，适合肠胃偏弱或想清淡收尾的晚上。',
      protein: '18～22g',
      calories: 400,
      tip: '需要更多蛋白时可加鸡胸丝 40g。',
    }),
    prepMinutes: 30,
    calories: 400,
    tags: '晚餐,清淡,养发,尿酸友好',
  }),
  recipe({
    templateKey: 'dinner-tofu-veggie-hotpot',
    title: '清汤蔬菜豆腐轻火锅',
    mealType: '晚餐',
    ingredients: [
      '主食｜粉丝（干）20g 或龙口粉丝少量｜约 70 千卡',
      '蛋白｜北豆腐 80g｜约 65 千卡',
      '蛋白｜鹌鹑蛋 4 个或鸡蛋 1 个｜约 75 千卡',
      '蔬菜｜白菜/生菜/菌菇/冬瓜 350g｜约 60 千卡',
      '汤底｜昆布蔬菜清汤（非牛油锅）｜约 30 千卡',
      '水果｜橙子半个｜约 35 千卡',
    ],
    steps: [
      '清水或昆布煮汤底，不放牛油、内脏、浓骨汤。',
      '蔬菜先下，豆腐与蛋后下；粉丝控量。',
      '蘸料用少量生抽+蒜，不放麻酱重油碟。',
      '橙子半个。',
    ],
    notes: mealNotes({
      focus: '把火锅做成清汤蔬菜局，满足聚餐感同时控嘌呤。',
      protein: '20～25g',
      calories: 335,
      tip: '不要毛肚黄喉虾滑拼盘；豆制品不过量。',
    }),
    prepMinutes: 40,
    calories: 335,
    tags: '晚餐,清汤,尿酸友好,少油',
  }),
  recipe({
    templateKey: 'dinner-oat-chicken-congee',
    title: '燕麦鸡丝蔬菜粥',
    mealType: '晚餐',
    ingredients: [
      '主食｜燕麦粥（燕麦片 40g）｜约 150 千卡',
      '蛋白｜鸡胸丝 70g｜约 115 千卡',
      '蔬菜｜青菜碎胡萝卜碎 150g｜约 35 千卡',
      '蔬菜｜香菇片 50g｜约 15 千卡',
      '调味｜少许姜丝生抽｜约 10 千卡',
      '水果｜苹果半个｜约 45 千卡',
    ],
    steps: [
      '燕麦加水煮开，下鸡丝、香菇同煮 8～10 分钟。',
      '青菜胡萝卜碎最后下锅烫熟。',
      '少盐少油；姜丝提味。',
      '苹果半个。',
    ],
    notes: mealNotes({
      focus: '一锅粥解决主食与蛋白，适合加班晚归的快速晚餐。',
      protein: '28～32g',
      calories: 370,
      tip: '不要改成排骨筒骨浓粥。',
    }),
    prepMinutes: 20,
    calories: 370,
    tags: '晚餐,快手,清淡,养发,尿酸友好',
  }),
];

export const SNACK_RECIPES = [
  recipe({
    templateKey: 'snack-fruit-nuts',
    title: '蓝莓杏仁轻加餐',
    mealType: '加餐',
    ingredients: [
      '水果｜蓝莓 100g｜约 55 千卡',
      '坚果｜杏仁 10g（约 8～10 粒）｜约 60 千卡',
      '饮品｜温开水｜约 0 千卡',
    ],
    steps: [
      '蓝莓洗净；杏仁原味无盐。',
      '两餐之间食用，不替代正餐蛋白。',
    ],
    notes: mealNotes({
      focus: '少量抗氧化水果 + 限量坚果，补健康脂肪。',
      protein: '3～5g',
      calories: 115,
      tip: '坚果不要一把抓；痛风发作期可去掉杏仁只留水果。',
    }),
    prepMinutes: 5,
    calories: 115,
    tags: '加餐,养发,尿酸友好,轻量',
  }),
  recipe({
    templateKey: 'snack-yogurt-berry',
    title: '无乳糖酸奶莓果杯',
    mealType: '加餐',
    ingredients: [
      '蛋白｜无乳糖无糖酸奶 150g｜约 80 千卡',
      '水果｜草莓/蓝莓 80g｜约 35 千卡',
      '谷物｜燕麦片 10g（可选）｜约 40 千卡',
    ],
    steps: [
      '酸奶倒入杯中，铺上浆果。',
      '可撒薄薄一层燕麦增加饱腹感。',
      '不另加蜂蜜白砂糖。',
    ],
    notes: mealNotes({
      focus: '乳糖友好的蛋白加餐，适合训练后或两餐间隔长时。',
      protein: '10～14g',
      calories: 155,
      tip: '确认包装“无乳糖”；不适者改水煮蛋 1 个。',
    }),
    prepMinutes: 5,
    calories: 155,
    tags: '加餐,乳糖友好,养发,高蛋白',
  }),
  recipe({
    templateKey: 'snack-egg-cucumber',
    title: '水煮蛋黄瓜解馋盘',
    mealType: '加餐',
    ingredients: [
      '蛋白｜水煮蛋 1 个｜约 75 千卡',
      '蔬菜｜黄瓜 150g｜约 20 千卡',
      '水果｜樱桃番茄 80g｜约 15 千卡',
    ],
    steps: [
      '鸡蛋提前煮好冷藏；黄瓜番茄洗净即食。',
      '可加极少量黑胡椒，不蘸甜酱。',
    ],
    notes: mealNotes({
      focus: '低负担咸味加餐，比饼干饮料更稳血糖与尿酸。',
      protein: '6～7g',
      calories: 110,
      tip: '不要配卤蛋重油或茶叶蛋过量盐。',
    }),
    prepMinutes: 10,
    calories: 110,
    tags: '加餐,鸡蛋,尿酸友好,轻量',
  }),
  recipe({
    templateKey: 'snack-kiwi-walnut',
    title: '猕猴桃核桃小份',
    mealType: '加餐',
    ingredients: [
      '水果｜猕猴桃 1 个｜约 50 千卡',
      '坚果｜核桃仁 8g（约 2 个半边）｜约 50 千卡',
    ],
    steps: [
      '猕猴桃去皮；核桃仁原味。',
      '作为下午茶替代含糖饮料。',
    ],
    notes: mealNotes({
      focus: '维 C + 少量欧米伽-3 脂肪，养发营养支持向加餐。',
      protein: '2～3g',
      calories: 100,
      tip: '核桃严格限量，不要一把。',
    }),
    prepMinutes: 5,
    calories: 100,
    tags: '加餐,养发,尿酸友好',
  }),
];

/** 日常饮品库（通用轻饮 / 谷物饮 / 乳糖友好饮） */
export const DRINK_RECIPES = [
  recipe({
    templateKey: 'drink-lemon-warm',
    title: '鲜柠檬温开水',
    mealType: '饮品',
    ingredients: [
      '饮品｜温开水 300mL｜约 0 千卡',
      '水果｜鲜柠檬片 2～3 片（约 15g）｜约 5 千卡',
    ],
    steps: [
      '温开水约 40～50℃，勿用滚烫水以免过苦。',
      '放入柠檬片浸泡 2～3 分钟后饮用；可再加 100mL 水续杯。',
      '不另加蔗糖、蜂蜜或果糖糖浆。',
    ],
    notes: mealNotes({
      focus: '最基础的无糖补水饮，替代含糖饮料与果汁。',
      protein: '0g',
      calories: 5,
      tip: '胃酸反流明显时可改纯温开水，少喝浓柠檬。',
    }),
    prepMinutes: 3,
    calories: 5,
    tags: '饮品,无糖,尿酸友好,补水',
  }),
  recipe({
    templateKey: 'drink-cucumber-mint',
    title: '黄瓜薄荷清爽水',
    mealType: '饮品',
    ingredients: [
      '饮品｜凉白开或温水 400mL｜约 0 千卡',
      '蔬菜｜黄瓜片 80g｜约 10 千卡',
      '配料｜新鲜薄荷叶 4～6 片｜约 1 千卡',
      '水果｜柠檬片 1 片（可选）｜约 2 千卡',
    ],
    steps: [
      '黄瓜洗净切片，薄荷搓揉出香气。',
      '放入壶中加水浸泡 10～15 分钟后饮用。',
      '可冷藏但不加冰块暴饮；当日喝完。',
    ],
    notes: mealNotes({
      focus: '几乎零负担的风味水，适合下午想喝饮料时替换可乐奶茶。',
      protein: '0～1g',
      calories: 13,
      tip: '不另加糖；薄荷过敏者去掉薄荷。',
    }),
    prepMinutes: 5,
    calories: 13,
    tags: '饮品,无糖,清爽,尿酸友好',
  }),
  recipe({
    templateKey: 'drink-chrysanthemum-goji',
    title: '菊花枸杞轻茶',
    mealType: '饮品',
    ingredients: [
      '饮品｜热水 300mL｜约 0 千卡',
      '配料｜干菊花 3～5 朵｜约 2 千卡',
      '配料｜枸杞 5～8 粒（约 3g）｜约 10 千卡',
    ],
    steps: [
      '菊花、枸杞用温水快速冲洗。',
      '热水冲泡 5～8 分钟，温热饮用。',
      '可续水 1 次；不放冰糖蜂蜜。',
    ],
    notes: mealNotes({
      focus: '清淡花茶补水，枸杞少量即可，避免当零食一把吃。',
      protein: '0～1g',
      calories: 12,
      tip: '体质偏寒或胃肠不适可减少菊花用量。',
    }),
    prepMinutes: 8,
    calories: 12,
    tags: '饮品,花茶,无糖,尿酸友好',
  }),
  recipe({
    templateKey: 'drink-lotus-lily',
    title: '莲子百合无豆温饮',
    mealType: '饮品',
    ingredients: [
      '干料｜去芯莲子 8g（约 10～12 粒）｜约 25 千卡',
      '干料｜干百合 8g｜约 25 千卡',
      '干料｜山药干 8g｜约 25 千卡',
      '谷物｜纯燕麦 10g｜约 40 千卡',
      '饮品｜清水约 350mL（成品 ≤250mL）｜约 0 千卡',
    ],
    steps: [
      '干料提前浸泡 4～6 小时，倒掉浸泡水并冲洗。',
      '加清水打细或小火煮软，制成约 250mL 无糖温饮。',
      '温热饮用，不冰镇；建议搭配主食或鸡蛋，避免空腹狂喝。',
    ],
    notes: mealNotes({
      focus: '无豆谷物温饮，痛风急性期也可作豆浆替代参考。',
      protein: '3～5g',
      calories: 115,
      tip: '单次 ≤250mL；不与大量豆制品同餐叠加。',
    }),
    prepMinutes: 20,
    calories: 115,
    tags: '饮品,无豆,谷物饮,尿酸友好,养发',
  }),
  recipe({
    templateKey: 'drink-yam-poria',
    title: '山药茯苓安神温饮',
    mealType: '饮品',
    ingredients: [
      '干料｜山药干 12g｜约 40 千卡',
      '干料｜茯苓 8g｜约 20 千卡',
      '干料｜去芯莲子 6g｜约 20 千卡',
      '干料｜干百合 6g｜约 20 千卡',
      '饮品｜清水约 350mL（成品 ≤250mL）｜约 0 千卡',
    ],
    steps: [
      '干料浸泡 4 小时，倒掉浸泡水。',
      '加水煮至软烂或破壁打细，温热饮用约 250mL。',
      '不放红枣、蔗糖、蜂蜜。',
    ],
    notes: mealNotes({
      focus: '完全无豆的安神向温饮，适合想少豆或急性期停豆时。',
      protein: '2～4g',
      calories: 100,
      tip: '茯苓过敏或医嘱限用者改用纯山药莲子百合。',
    }),
    prepMinutes: 25,
    calories: 100,
    tags: '饮品,无豆,安神,尿酸友好',
  }),
  recipe({
    templateKey: 'drink-lactose-oat',
    title: '无乳糖奶燕麦轻饮',
    mealType: '饮品',
    ingredients: [
      '蛋白｜无乳糖低脂牛奶 200mL｜约 80 千卡',
      '谷物｜纯燕麦片 15g｜约 55 千卡',
      '水果｜蓝莓 40g（可选）｜约 20 千卡',
      '配料｜肉桂粉极少许（可选）｜约 2 千卡',
    ],
    steps: [
      '燕麦与无乳糖奶小火煮 5～8 分钟至微稠，或冷藏隔夜泡软后温热。',
      '可加入洗净蓝莓；不放糖浆炼乳。',
      '当作加餐饮或早餐饮料部分，勿一次喝超大杯。',
    ],
    notes: mealNotes({
      focus: '乳糖友好的蛋白谷物饮，比奶茶负担低。',
      protein: '10～12g',
      calories: 155,
      tip: '买不到无乳糖奶可换无乳糖无糖酸奶 150g + 温水稀释。',
    }),
    prepMinutes: 10,
    calories: 155,
    tags: '饮品,乳糖友好,燕麦,养发',
  }),
  recipe({
    templateKey: 'drink-berry-smoothie',
    title: '莓果无乳糖酸奶昔',
    mealType: '饮品',
    ingredients: [
      '蛋白｜无乳糖无糖酸奶 150g｜约 80 千卡',
      '水果｜冷冻或鲜蓝莓/草莓 100g｜约 45 千卡',
      '饮品｜清水或无乳糖奶 50mL｜约 20 千卡',
      '配料｜奇亚籽 3g（可选）｜约 15 千卡',
    ],
    steps: [
      '材料入破壁机打至顺滑，立即饮用。',
      '稠可再加少量水；不另加香蕉过多或蜂蜜。',
      '训练后或两餐之间饮用较合适。',
    ],
    notes: mealNotes({
      focus: '含优质蛋白与花青素的轻昔，养发营养支持向。',
      protein: '10～14g',
      calories: 160,
      tip: '仍腹胀则去掉酸奶，改清水+莓果+水煮蛋另吃。',
    }),
    prepMinutes: 5,
    calories: 160,
    tags: '饮品,乳糖友好,高蛋白,养发',
  }),
  recipe({
    templateKey: 'drink-tomato-warm',
    title: '无糖番茄温饮',
    mealType: '饮品',
    ingredients: [
      '蔬菜｜熟番茄/番茄 200g｜约 35 千卡',
      '饮品｜温开水 100mL｜约 0 千卡',
      '配料｜少许黑胡椒（可选）｜约 1 千卡',
    ],
    steps: [
      '番茄去皮切块，加水略煮软或直接打成蓉后温热。',
      '可加极少量黑胡椒；不放糖、不放浓奶油。',
      '总量约 250～300mL，当作餐前开胃或下午饮品。',
    ],
    notes: mealNotes({
      focus: '天然番茄饮，补充钾与维 C，比罐装含糖番茄汁更合适。',
      protein: '1～2g',
      calories: 36,
      tip: '胃食管反流明显时避免空腹喝过酸版本。',
    }),
    prepMinutes: 10,
    calories: 36,
    tags: '饮品,无糖,番茄,尿酸友好',
  }),
  recipe({
    templateKey: 'drink-green-soy-light',
    title: '小份绿豆百合轻豆浆',
    mealType: '饮品',
    ingredients: [
      '干料｜绿豆 12g｜约 40 千卡',
      '干料｜干百合 8g｜约 25 千卡',
      '干料｜山药干 8g｜约 25 千卡',
      '谷物｜燕麦 10g｜约 40 千卡',
      '饮品｜清水约 350mL（成品 ≤250mL）｜约 0 千卡',
    ],
    steps: [
      '干料浸泡 4 小时，倒掉浸泡水降低嘌呤溶出。',
      '打细并彻底煮熟，成品控制在 250mL 以内，温饮。',
      '搭配鸡蛋或杂粮，不空腹作唯一一餐。',
    ],
    notes: mealNotes({
      focus: '豆类干重严控的小份豆浆向饮品。',
      protein: '5～8g',
      calories: 130,
      tip: '痛风急性期停用，改山药茯苓莲子百合温饮。',
    }),
    prepMinutes: 25,
    calories: 130,
    tags: '饮品,少豆,尿酸友好,谷物饮',
  }),
  recipe({
    templateKey: 'drink-americano-lactose',
    title: '美式咖啡+无乳糖奶轻配',
    mealType: '饮品',
    ingredients: [
      '饮品｜美式咖啡（无糖）200mL｜约 5 千卡',
      '蛋白｜无乳糖低脂牛奶 80mL｜约 30 千卡',
    ],
    steps: [
      '冲泡无糖美式，放至不烫口。',
      '兑入无乳糖低脂奶 80mL，不放糖浆奶盖。',
      '下午 4 点后若影响睡眠可改无咖啡因谷物饮。',
    ],
    notes: mealNotes({
      focus: '比奶茶轻很多的咖啡选项；咖啡因因人而异。',
      protein: '3～4g',
      calories: 35,
      tip: '尿酸管理仍应避免含糖咖啡饮料与酒精。',
    }),
    prepMinutes: 5,
    calories: 35,
    tags: '饮品,咖啡,乳糖友好,无糖',
  }),
  recipe({
    templateKey: 'drink-apple-cinnamon',
    title: '苹果肉桂温果饮',
    mealType: '饮品',
    ingredients: [
      '水果｜苹果块 120g（约半个）｜约 60 千卡',
      '饮品｜清水 250mL｜约 0 千卡',
      '配料｜肉桂粉极少许｜约 2 千卡',
    ],
    steps: [
      '苹果切块加水小火煮 8～10 分钟至软，可轻轻压碎。',
      '撒极少量肉桂；不放冰糖蜂蜜。',
      '连果肉温饮，或滤渣只喝汤（热量略低）。',
    ],
    notes: mealNotes({
      focus: '用整果煮饮替代果汁，纤维保留更好、升糖更缓。',
      protein: '0～1g',
      calories: 62,
      tip: '当作加餐饮料时，注意与正餐水果总量别叠太多。',
    }),
    prepMinutes: 12,
    calories: 62,
    tags: '饮品,水果,无糖,尿酸友好',
  }),
  recipe({
    templateKey: 'drink-ginger-warm',
    title: '生姜红枣替代｜淡姜温水',
    mealType: '饮品',
    ingredients: [
      '饮品｜温开水 300mL｜约 0 千卡',
      '配料｜鲜姜丝/姜片 3～5g｜约 5 千卡',
      '配料｜柠檬片 1 片（可选）｜约 2 千卡',
    ],
    steps: [
      '姜片用热水冲泡或略煮 3 分钟，制成淡姜温水。',
      '不放红枣、冰糖（本库默认避开高糖干果甜饮）。',
      '胃寒可少量；胃热或反流明显则减量或停用。',
    ],
    notes: mealNotes({
      focus: '暖胃淡饮，刻意不做姜枣甜茶，避免隐性糖分。',
      protein: '0g',
      calories: 7,
      tip: '不是治疗饮；肠胃疾病请遵医嘱。',
    }),
    prepMinutes: 5,
    calories: 7,
    tags: '饮品,无糖,暖胃,尿酸友好',
  }),
];

export const MEAL_RECIPES = [...LUNCH_RECIPES, ...DINNER_RECIPES, ...SNACK_RECIPES, ...DRINK_RECIPES];
