/**
 * 来源：《其他食谱新方案.md》
 * 按原文直接转换，不做配方改写。
 */

export const SOY_MILK_ADAPTATION = '适配：糖尿病/高血压/高尿酸/高血脂/脱发/失眠/胃食管反流';

export const SOY_MILK_CORE_RULES = [
  '油脂类：黑芝麻≤6g、核桃≤8g、花生仅周六1次≤10g',
  '高嘌呤豆单日总和≤50g；黑豆≤15g、黄豆≤12g、红腰豆一周2次',
  '精制杂粮（红米/黑米/小米/糙米）单日合计≤15g',
  '藜麦单次≤10g；所有杂粮提前浸泡4h，倒掉泡水解胀气、降嘌呤',
  '燕麦统一裸燕麦米；总干料稳定117-122g',
].join('\n');

export const SOY_MILK_DRINKING_NOTES = [
  '控糖：全程不加糖、红枣、桂圆、玉米碎；必须保留豆渣；红米/黑米/小米/糙米每日总量不超15g，防止碳水超标升糖。',
  '高尿酸：杂豆单日总重不超50g，周日无豆缓冲；食材浸泡后倒掉泡豆水，减少30%嘌呤；痛风红肿期停用黑豆、黄豆、红腰豆、花生。',
  '高血压：全部高钾食材，日常严格低盐饮食搭配饮用。',
  '高血脂：每日裸燕麦米稳定降脂；黑芝麻、核桃、花生严格控量，不可随意加。',
  '脱发：黑豆、黑米、黑芝麻、核桃分天搭配，依靠山药芡实健脾补气养血，不依赖大量豆类。',
  '失眠：睡前2小时禁止饮用，避免夜尿打断睡眠；下午3点可少量温饮加餐。',
  '胃食管反流：全部食材浸泡至软烂；胀气严重可每份额外加2g陈皮同打；全程40℃温饮，禁止冰镇、空腹单喝。',
  '大便调整：干结：增加裸燕麦米、黑芝麻，减少芡实、莲子；容易腹泻：减少糙米、藜麦、绿豆，剔除花生。',
].join('\n');

const SHARED_STEPS = [
  '统一标准红线',
  SOY_MILK_CORE_RULES,
  '',
  '食材轮换说明',
  '炒白扁豆仅周二、周四、周六三天安排，一周3次，频次适中，既保留健脾护胃、控尿酸的核心作用，又不会天天重复；',
  '其余四天完全不用白扁豆，依靠山药、茯苓、藜麦、糙米调和肠胃，避免食材单一；',
  '所有养发、安神、控压、控糖食材均匀分散在七天，营养均衡不扎堆；',
].join('\n');

function buildNotes(effect, calories) {
  return [
    effect,
    `参考热量：约 ${calories} 千卡/份（按所列干料制成一杯 ≤250ml 估算，实际因过滤与留渣略有浮动）。`,
    '',
    '全套饮用统一须知',
    SOY_MILK_DRINKING_NOTES,
  ].join('\n');
}

export const SOY_MILK_RECIPES = [
  {
    templateKey: 'soy-rotation-d1',
    planDay: 1,
    title: '周一｜莲子黑豆百合安神款（失眠燥热、养发）',
    mealType: '饮品',
    ingredients: [
      '总干料120g',
      '黑豆12g',
      '黑米8g',
      '红米5g',
      '藜麦8g',
      '黑芝麻5g',
      '去芯莲子18g',
      '干百合20g',
      '山药干22g',
      '茯苓15g',
      '裸燕麦米12g',
    ].join('\n'),
    steps: SHARED_STEPS,
    notes: buildNotes('功效：黑豆黑米黑芝麻养发；莲子百合安神；无扁豆，清爽不滋腻，适合容易上火人群', 360),
    prepMinutes: 20,
    calories: 360,
    tags: '豆浆轮换,周一,安神,养发',
  },
  {
    templateKey: 'soy-rotation-d2',
    planDay: 2,
    title: '周二｜炒白扁豆芡实固肾款（第1天白扁豆，脱发夜尿）',
    mealType: '饮品',
    ingredients: [
      '总干料122g',
      '炒白扁豆20g',
      '黑豆15g',
      '红腰豆10g',
      '小米8g',
      '糙米7g',
      '核桃8g',
      '芡实19g',
      '山药干23g',
      '茯苓16g',
      '去芯莲子14g',
      '裸燕麦米2g',
    ].join('\n'),
    steps: SHARED_STEPS,
    notes: buildNotes('功效：白扁豆健脾祛湿中和豆类胀气；芡实固肾减少起夜，多重杂粮补足气血', 370),
    prepMinutes: 20,
    calories: 370,
    tags: '豆浆轮换,周二,固肾,养发',
  },
  {
    templateKey: 'soy-rotation-d3',
    planDay: 3,
    title: '周三｜赤小豆红米消水肿款（下肢浮肿、高血压）',
    mealType: '饮品',
    ingredients: [
      '总干料119g',
      '赤小豆18g',
      '黄豆10g',
      '黑米7g',
      '藜麦7g',
      '黑芝麻4g',
      '山药干21g',
      '茯苓17g',
      '干百合16g',
      '裸燕麦米14g',
    ].join('\n'),
    steps: SHARED_STEPS,
    notes: buildNotes('功效：赤小豆茯苓利水排钠降压；低嘌呤，减轻身体沉重黏腻感', 350),
    prepMinutes: 20,
    calories: 350,
    tags: '豆浆轮换,周三,消水肿,降压',
  },
  {
    templateKey: 'soy-rotation-d4',
    planDay: 4,
    title: '周四｜炒白扁豆四神养胃款（反酸、血糖不稳）',
    mealType: '饮品',
    ingredients: [
      '总干料121g',
      '炒白扁豆22g',
      '黄豆8g',
      '红米6g',
      '小米7g',
      '糙米6g',
      '核桃6g',
      '芡实17g',
      '山药干24g',
      '茯苓18g',
      '去芯莲子15g',
      '裸燕麦米11g',
    ].join('\n'),
    steps: SHARED_STEPS,
    notes: buildNotes('功效：四神组合+炒白扁豆收敛胃酸，缓解烧心，温和平稳餐后血糖', 360),
    prepMinutes: 20,
    calories: 360,
    tags: '豆浆轮换,周四,四神,养胃',
  },
  {
    templateKey: 'soy-rotation-d5',
    planDay: 5,
    title: '周五｜鹰嘴豆红腰豆滋养款（体虚易饿、掉发多）',
    mealType: '饮品',
    ingredients: [
      '总干料118g',
      '鹰嘴豆15g',
      '黑豆10g',
      '红腰豆8g',
      '黑米6g',
      '藜麦9g',
      '黑芝麻6g',
      '山药干22g',
      '干百合17g',
      '茯苓15g',
      '裸燕麦米7g',
    ].join('\n'),
    steps: SHARED_STEPS,
    notes: buildNotes('功效：多种优质植物蛋白滋养头皮；藜麦增强饱腹感，缓解饥饿心慌', 360),
    prepMinutes: 20,
    calories: 360,
    tags: '豆浆轮换,周五,滋养,养发',
  },
  {
    templateKey: 'soy-rotation-d6',
    planDay: 6,
    title: '周六｜炒白扁豆绿豆清暑款（三伏上火，唯一含花生）',
    mealType: '饮品',
    ingredients: [
      '总干料117g',
      '炒白扁豆18g',
      '绿豆14g',
      '黄豆7g',
      '小米9g',
      '花生10g',
      '山药干23g',
      '茯苓16g',
      '干百合21g',
      '裸燕麦米13g',
    ].join('\n'),
    steps: SHARED_STEPS,
    notes: buildNotes('功效：白扁豆中和绿豆寒性；少量花生补充微量元素，痛风发作期直接去掉花生', 345),
    prepMinutes: 20,
    calories: 345,
    tags: '豆浆轮换,周六,清暑,降火',
  },
  {
    templateKey: 'soy-rotation-d7',
    planDay: 7,
    title: '周日｜无豆纯杂粮安神款（无豆类、无白扁豆，护肾低嘌呤）',
    mealType: '饮品',
    ingredients: [
      '总干料120g',
      '山药干30g',
      '茯苓22g',
      '芡实16g',
      '去芯莲子20g',
      '干百合18g',
      '黑米7g',
      '小米7g',
      '藜麦8g',
      '糙米5g',
      '黑芝麻5g',
      '核桃7g',
      '裸燕麦米8g',
    ].join('\n'),
    steps: SHARED_STEPS,
    notes: buildNotes('功效：零豆类彻底降低尿酸代谢压力；杂粮搭配健脾养心，给肝肾休息时间', 340),
    prepMinutes: 20,
    calories: 340,
    tags: '豆浆轮换,周日,无豆,安神',
  },
];
